"use client";

import {
  Image,
  Aperture,
  FilmStrip,
  Stack,
  SquaresFour,
  Rows,
  PenNib,
  Cursor,
  Camera,
  FilePdf,
  ArrowsClockwise,
  ArrowsOut,
  DeviceMobile,
  FileCode,
  Plus,
  Scissors,
  ArrowClockwise,
  Lock,
  LockOpen,
  Stamp,
  Hash,
  Crop,
  MinusCircle,
  ArrowsDownUp,
  Images,
  PencilSimple,
  MagnifyingGlass,
  Columns,
  QrCode,
  Scan,
  FileZip,
  Eraser,
  Gauge,
  FlipHorizontal,
  Sliders,
  CornersOut,
  FrameCorners,
  Palette,
  Square,
  GridFour,
  PaintBucket,
  Browsers,
  BoundingBox,
  BracketsCurly,
  Waveform,
  Eyedropper,
  Gradient,
  CircleHalf,
  Swatches,
  PaintRoller,
  Eye,
  SelectionBackground,
  Shuffle,
  Fingerprint,
} from "@phosphor-icons/react";

export const TOOL_ICONS: Record<string, React.ReactNode> = {
  "/tools/png-to-webp": <Image size={22} />,
  "/tools/jpg-to-webp": <Aperture size={22} />,
  "/tools/gif-to-webp": <FilmStrip size={22} />,
  "/tools/avif-to-webp": <Stack size={22} />,
  "/tools/bmp-to-webp": <SquaresFour size={22} />,
  "/tools/tiff-to-webp": <Rows size={22} />,
  "/tools/svg-to-webp": <PenNib size={22} />,
  "/tools/ico-to-webp": <Cursor size={22} />,
  "/tools/jfif-to-webp": <Camera size={22} />,
  "/tools/pdf-to-webp": <FilePdf size={22} />,
  "/tools/webp-to-webp": <ArrowsClockwise size={22} />,
  "/tools/webp-resizer": <ArrowsOut size={22} />,
  "/tools/heic-to-webp": <DeviceMobile size={22} />,
  "/tools/heic-resizer": <DeviceMobile size={22} />,
  "/tools/heic-to-png": <DeviceMobile size={22} />,
  "/tools/heic-to-jpg": <DeviceMobile size={22} />,
  "/tools/png-resizer": <Image size={22} />,
  "/tools/jpg-resizer": <Aperture size={22} />,
  "/tools/html-to-pdf": <FileCode size={22} />,
  "/tools/jpg-to-pdf": <Aperture size={22} />,
  "/tools/png-to-pdf": <Image size={22} />,
  "/tools/webp-to-pdf": <ArrowsClockwise size={22} />,
  "/tools/heic-to-pdf": <DeviceMobile size={22} />,
  "/tools/bmp-to-pdf": <SquaresFour size={22} />,
  "/tools/tiff-to-pdf": <Rows size={22} />,
  "/tools/gif-to-pdf": <FilmStrip size={22} />,
  "/tools/svg-to-pdf": <PenNib size={22} />,
  "/tools/avif-to-pdf": <Stack size={22} />,
  "/tools/ico-to-pdf": <Cursor size={22} />,
  "/tools/jfif-to-pdf": <Camera size={22} />,
  "/tools/merge-pdf": <Plus size={22} />,
  "/tools/split-pdf": <Scissors size={22} />,
  "/tools/rotate-pdf": <ArrowClockwise size={22} />,
  "/tools/protect-pdf": <Lock size={22} />,
  "/tools/unlock-pdf": <LockOpen size={22} />,
  "/tools/watermark-pdf": <Stamp size={22} />,
  "/tools/pdf-page-numbers": <Hash size={22} />,
  "/tools/crop-pdf": <Crop size={22} />,
  "/tools/rearrange-pdf": <ArrowsDownUp size={22} />,
  "/tools/pdf-to-images": <Images size={22} />,
  "/tools/sign-pdf": <PencilSimple size={22} />,
  "/tools/ocr-pdf": <MagnifyingGlass size={22} />,
  "/tools/edit-pdf": <PencilSimple size={22} />,
  "/tools/compare-pdf": <Columns size={22} />,
  "/tools/qr-code-generator": <QrCode size={22} />,
  "/tools/qr-code-reader": <Scan size={22} />,
  "/tools/qr-code-with-logo": <QrCode size={22} />,
  "/tools/batch-qr-generator": <FileZip size={22} />,
  "/tools/image-compressor": <Gauge size={22} />,
  "/tools/image-cropper": <Crop size={22} />,
  "/tools/background-remover": <Eraser size={22} />,
  "/tools/favicon-generator": <FileZip size={22} />,
  "/tools/image-flip-rotate": <FlipHorizontal size={22} />,
  "/tools/photo-adjustments": <Sliders size={22} />,
  "/tools/image-watermark": <Stamp size={22} />,
  "/tools/image-resizer": <CornersOut size={22} />,
  "/tools/rounded-corners": <FrameCorners size={22} />,
  "/tools/color-palette": <Palette size={22} />,
  "/tools/image-border": <Square size={22} />,
  "/tools/image-collage": <GridFour size={22} />,
  "/tools/grayscale-tint": <PaintBucket size={22} />,
  "/tools/social-media-resizer": <Browsers size={22} />,
  "/tools/image-padding": <BoundingBox size={22} />,
  "/tools/image-to-base64": <BracketsCurly size={22} />,
  "/tools/noise-grain": <Waveform size={22} />,
  "/tools/color-picker": <Eyedropper size={22} />,
  "/tools/gradient-generator": <Gradient size={22} />,
  "/tools/contrast-checker": <CircleHalf size={22} />,
  "/tools/color-palette-generator": <Swatches size={22} />,
  "/tools/tint-shade-generator": <PaintRoller size={22} />,
  "/tools/color-blindness-simulator": <Eye size={22} />,
  "/tools/shadow-generator": <SelectionBackground size={22} />,
  "/tools/random-color-generator": <Shuffle size={22} />,
  "/remove-pdf-pages": <MinusCircle size={22} />,
  "/tools/plagiarism-checker": <Fingerprint size={22} />,
};
