"use client";

import {
  Image,
  Aperture,
  FilmStrip,
  Stack,
  SquaresFour,
  Rows,
  PenNib,
  Cursor,
  Camera,
  FilePdf,
  ArrowsClockwise,
  ArrowsOut,
  DeviceMobile,
  FileCode,
  Plus,
  Scissors,
  ArrowClockwise,
  Lock,
  LockOpen,
  Stamp,
  Hash,
  Crop,
  MinusCircle,
  ArrowsDownUp,
  Images,
  PencilSimple,
  MagnifyingGlass,
  Columns,
  QrCode,
  Scan,
  FileZip,
  Eraser,
  Gauge,
  FlipHorizontal,
  Sliders,
  CornersOut,
  FrameCorners,
  Palette,
  Square,
  GridFour,
  PaintBucket,
  Browsers,
  BoundingBox,
  BracketsCurly,
  Waveform,
  Eyedropper,
  Gradient,
  CircleHalf,
  Swatches,
  PaintRoller,
  Eye,
  SelectionBackground,
  Shuffle,
  Fingerprint,
  TextT,
  TextAa,
  Article,
  TextB,
  TextItalic,
  TextStrikethrough,
  MagicWand,
  Star,
  Fire,
  Crosshair,
  Key,
  ArrowCounterClockwise,
  Repeat,
  UserCircle,
  Code,
  LinkSimple,
  IdentificationCard,
  ArrowsHorizontal,
  GameController,
  Radio,
  Smiley,
  Detective,
  Table,
  ChartBar,
  Tag,
  CalendarBlank,
  Clock,
  Certificate,
  Ruler,
  Scales,
  Thermometer,
  Lightning,
  CornersIn,
  Cylinder,
  ArrowsIn,
  BatteryFull,
  HardDrive,
  Hourglass,
  Compass,
  GasPump,
  Percent,
  Receipt,
  Heartbeat,
  ChartLineUp,
  Bank,
  Quotes,
  Terminal,
  Wallet,
  MathOperations,
  GraduationCap,
} from "@phosphor-icons/react";

export const TOOL_ICONS: Record<string, React.ReactNode> = {
  "/tools/png-to-webp": <Image size={22} />,
  "/tools/jpg-to-webp": <Aperture size={22} />,
  "/tools/gif-to-webp": <FilmStrip size={22} />,
  "/tools/avif-to-webp": <Stack size={22} />,
  "/tools/bmp-to-webp": <SquaresFour size={22} />,
  "/tools/tiff-to-webp": <Rows size={22} />,
  "/tools/svg-to-webp": <PenNib size={22} />,
  "/tools/ico-to-webp": <Cursor size={22} />,
  "/tools/jfif-to-webp": <Camera size={22} />,
  "/tools/pdf-to-webp": <FilePdf size={22} />,
  "/tools/webp-to-webp": <ArrowsClockwise size={22} />,
  "/tools/webp-resizer": <ArrowsOut size={22} />,
  "/tools/heic-to-webp": <DeviceMobile size={22} />,
  "/tools/heic-resizer": <DeviceMobile size={22} />,
  "/tools/heic-to-png": <DeviceMobile size={22} />,
  "/tools/heic-to-jpg": <DeviceMobile size={22} />,
  "/tools/png-resizer": <Image size={22} />,
  "/tools/jpg-resizer": <Aperture size={22} />,
  "/tools/html-to-pdf": <FileCode size={22} />,
  "/tools/jpg-to-pdf": <Aperture size={22} />,
  "/tools/png-to-pdf": <Image size={22} />,
  "/tools/webp-to-pdf": <ArrowsClockwise size={22} />,
  "/tools/heic-to-pdf": <DeviceMobile size={22} />,
  "/tools/bmp-to-pdf": <SquaresFour size={22} />,
  "/tools/tiff-to-pdf": <Rows size={22} />,
  "/tools/gif-to-pdf": <FilmStrip size={22} />,
  "/tools/svg-to-pdf": <PenNib size={22} />,
  "/tools/avif-to-pdf": <Stack size={22} />,
  "/tools/ico-to-pdf": <Cursor size={22} />,
  "/tools/jfif-to-pdf": <Camera size={22} />,
  "/tools/merge-pdf": <Plus size={22} />,
  "/tools/split-pdf": <Scissors size={22} />,
  "/tools/rotate-pdf": <ArrowClockwise size={22} />,
  "/tools/protect-pdf": <Lock size={22} />,
  "/tools/unlock-pdf": <LockOpen size={22} />,
  "/tools/watermark-pdf": <Stamp size={22} />,
  "/tools/pdf-page-numbers": <Hash size={22} />,
  "/tools/crop-pdf": <Crop size={22} />,
  "/tools/rearrange-pdf": <ArrowsDownUp size={22} />,
  "/tools/pdf-to-images": <Images size={22} />,
  "/tools/sign-pdf": <PencilSimple size={22} />,
  "/tools/ocr-pdf": <MagnifyingGlass size={22} />,
  "/tools/edit-pdf": <PencilSimple size={22} />,
  "/tools/compare-pdf": <Columns size={22} />,
  "/tools/qr-code-generator": <QrCode size={22} />,
  "/tools/qr-code-reader": <Scan size={22} />,
  "/tools/qr-code-with-logo": <QrCode size={22} />,
  "/tools/batch-qr-generator": <FileZip size={22} />,
  "/tools/image-compressor": <Gauge size={22} />,
  "/tools/image-cropper": <Crop size={22} />,
  "/tools/background-remover": <Eraser size={22} />,
  "/tools/favicon-generator": <FileZip size={22} />,
  "/tools/image-flip-rotate": <FlipHorizontal size={22} />,
  "/tools/photo-adjustments": <Sliders size={22} />,
  "/tools/image-watermark": <Stamp size={22} />,
  "/tools/image-resizer": <CornersOut size={22} />,
  "/tools/rounded-corners": <FrameCorners size={22} />,
  "/tools/color-palette": <Palette size={22} />,
  "/tools/image-border": <Square size={22} />,
  "/tools/image-collage": <GridFour size={22} />,
  "/tools/grayscale-tint": <PaintBucket size={22} />,
  "/tools/social-media-resizer": <Browsers size={22} />,
  "/tools/image-padding": <BoundingBox size={22} />,
  "/tools/image-to-base64": <BracketsCurly size={22} />,
  "/tools/noise-grain": <Waveform size={22} />,
  "/tools/color-picker": <Eyedropper size={22} />,
  "/tools/gradient-generator": <Gradient size={22} />,
  "/tools/contrast-checker": <CircleHalf size={22} />,
  "/tools/color-palette-generator": <Swatches size={22} />,
  "/tools/tint-shade-generator": <PaintRoller size={22} />,
  "/tools/color-blindness-simulator": <Eye size={22} />,
  "/tools/shadow-generator": <SelectionBackground size={22} />,
  "/tools/random-color-generator": <Shuffle size={22} />,
  "/remove-pdf-pages": <MinusCircle size={22} />,
  "/tools/plagiarism-checker": <Fingerprint size={22} />,
  "/tools/lorem-ipsum": <TextT size={22} />,
  "/tools/text-case-converter": <TextAa size={22} />,
  "/tools/word-counter": <Article size={22} />,
  "/tools/fancy-text": <MagicWand size={22} />,
  "/tools/bold-text-generator": <TextB size={22} />,
  "/tools/italic-text-generator": <TextItalic size={22} />,
  "/tools/strikethrough-text": <TextStrikethrough size={22} />,
  "/tools/stylish-name-generator": <Star size={22} />,
  "/tools/free-fire-name-generator": <Fire size={22} />,
  "/tools/pubg-name-generator": <Crosshair size={22} />,
  "/tools/password-generator": <Key size={22} />,
  "/tools/hashtag-generator": <Hash size={22} />,
  "/tools/reverse-text": <ArrowCounterClockwise size={22} />,
  "/tools/text-repeater": <Repeat size={22} />,
  "/tools/random-name-generator": <UserCircle size={22} />,
  "/tools/json-formatter": <Code size={22} />,
  "/tools/base64-text": <BracketsCurly size={22} />,
  "/tools/url-encoder": <LinkSimple size={22} />,
  "/tools/uuid-generator": <IdentificationCard size={22} />,
  "/tools/diff-checker": <ArrowsHorizontal size={22} />,
  "/tools/leet-speak": <GameController size={22} />,
  "/tools/morse-code": <Radio size={22} />,
  "/tools/emoji-text": <Smiley size={22} />,
  "/tools/rot13": <Detective size={22} />,
  "/tools/markdown-preview": <Eye size={22} />,
  "/tools/html-encoder": <Code size={22} />,
  "/tools/regex-tester": <MagnifyingGlass size={22} />,
  "/tools/number-to-words": <Hash size={22} />,
  "/tools/ascii-art": <GridFour size={22} />,
  "/tools/char-frequency": <ChartBar size={22} />,
  "/tools/text-to-slug": <Tag size={22} />,
  "/tools/csv-to-json": <Table size={22} />,
  "/tools/json-to-csv": <Table size={22} />,
  "/tools/crontab-explainer": <CalendarBlank size={22} />,
  "/tools/unix-timestamp": <Clock size={22} />,
  "/tools/jwt-decoder": <Certificate size={22} />,
  "/tools/length-converter": <Ruler size={22} />,
  "/tools/weight-converter": <Scales size={22} />,
  "/tools/temperature-converter": <Thermometer size={22} />,
  "/tools/speed-converter": <Lightning size={22} />,
  "/tools/area-converter": <CornersIn size={22} />,
  "/tools/volume-converter": <Cylinder size={22} />,
  "/tools/pressure-converter": <ArrowsIn size={22} />,
  "/tools/energy-converter": <BatteryFull size={22} />,
  "/tools/data-storage-converter": <HardDrive size={22} />,
  "/tools/time-converter": <Hourglass size={22} />,
  "/tools/angle-converter": <Compass size={22} />,
  "/tools/fuel-converter": <GasPump size={22} />,
  "/tools/yaml-to-json": <Code size={22} />,
  "/tools/xml-formatter": <Quotes size={22} />,
  "/tools/string-escape": <Terminal size={22} />,
  "/tools/base-converter": <Hash size={22} />,
  "/tools/percentage-calculator": <Percent size={22} />,
  "/tools/tip-calculator": <Receipt size={22} />,
  "/tools/bmi-calculator": <Heartbeat size={22} />,
  "/tools/compound-interest": <ChartLineUp size={22} />,
  "/tools/loan-calculator": <Bank size={22} />,
  "/tools/age-calculator": <CalendarBlank size={22} />,
  "/tools/date-difference": <ArrowsHorizontal size={22} />,
  "/tools/discount-calculator": <Tag size={22} />,
  "/tools/sales-tax-calculator": <Percent size={22} />,
  "/tools/calorie-calculator": <Fire size={22} />,
  "/tools/fuel-cost-calculator": <GasPump size={22} />,
  "/tools/hours-calculator": <Clock size={22} />,
  "/tools/unit-price-calculator": <Scales size={22} />,
  "/tools/electricity-cost-calculator": <Lightning size={22} />,
  "/tools/salary-calculator": <Wallet size={22} />,
  "/tools/margin-calculator": <MathOperations size={22} />,
  "/tools/roi-calculator": <ChartLineUp size={22} />,
  "/tools/savings-goal-calculator": <Bank size={22} />,
  "/tools/gpa-calculator": <GraduationCap size={22} />,
};
