export const CATEGORIES = [
  { id: "all", label: "All" },
  { id: "webp", label: "WebP Tools" },
  { id: "pdf", label: "Image to PDF" },
  { id: "pdf-tools", label: "PDF Tools" },
] as const;

export type CategoryId = (typeof CATEGORIES)[number]["id"];

export const TOOLS = [
  {
    href: "/png-to-webp",
    name: "PNG → WebP",
    shortName: "PNG to WebP Converter",
    description: "Convert PNG images to WebP format. Dramatically smaller files at the same visual quality.",
    badge: "Lossless source",
    category: "webp" as CategoryId,
  },
  {
    href: "/jpg-to-webp",
    name: "JPG → WebP",
    shortName: "JPG to WebP Converter",
    description: "Convert JPEG photos to WebP. Up to 34% smaller than JPEG at comparable quality.",
    badge: "Lossy optimized",
    category: "webp" as CategoryId,
  },
  {
    href: "/gif-to-webp",
    name: "GIF → WebP",
    shortName: "GIF to WebP Converter",
    description: "Convert GIF images to WebP for smaller static frames and more efficient compression.",
    badge: "Static frame",
    category: "webp" as CategoryId,
  },
  {
    href: "/avif-to-webp",
    name: "AVIF → WebP",
    shortName: "AVIF to WebP Converter",
    description: "Convert AVIF images to WebP for broader browser compatibility. No upload required.",
    badge: "Modern format",
    category: "webp" as CategoryId,
  },
  {
    href: "/bmp-to-webp",
    name: "BMP → WebP",
    shortName: "BMP to WebP Converter",
    description: "Convert uncompressed BMP files to WebP. Achieve massive size reduction instantly.",
    badge: "Uncompressed in",
    category: "webp" as CategoryId,
  },
  {
    href: "/tiff-to-webp",
    name: "TIFF → WebP",
    shortName: "TIFF to WebP Converter",
    description: "Convert high-resolution TIFF images to lightweight WebP for web use.",
    badge: "High-res source",
    category: "webp" as CategoryId,
  },
  {
    href: "/svg-to-webp",
    name: "SVG → WebP",
    shortName: "SVG to WebP Converter",
    description: "Rasterize SVG vector graphics to WebP. Crisp output at your chosen quality.",
    badge: "Vector to raster",
    category: "webp" as CategoryId,
  },
  {
    href: "/ico-to-webp",
    name: "ICO → WebP",
    shortName: "ICO to WebP Converter",
    description: "Extract and convert ICO icon files to WebP. Great for repurposing favicons.",
    badge: "Icon extract",
    category: "webp" as CategoryId,
  },
  {
    href: "/jfif-to-webp",
    name: "JFIF → WebP",
    shortName: "JFIF to WebP Converter",
    description: "Convert JFIF photos to WebP. JFIF is a JPEG variant — get up to 34% smaller files.",
    badge: "JPEG variant",
    category: "webp" as CategoryId,
  },
  {
    href: "/pdf-to-webp",
    name: "PDF → WebP",
    shortName: "PDF to WebP Converter",
    description: "Convert the first page of a PDF document to a WebP image for thumbnails and previews.",
    badge: "First page",
    category: "webp" as CategoryId,
  },
  {
    href: "/webp-to-webp",
    name: "WebP Re-optimize",
    shortName: "WebP Re-optimizer",
    description: "Re-compress an existing WebP file at a different quality level to fine-tune file size.",
    badge: "Re-compress",
    category: "webp" as CategoryId,
  },
  {
    href: "/webp-resizer",
    name: "WebP Resizer",
    shortName: "Image to WebP Resizer",
    description: "Resize any image to custom dimensions and export as WebP. Aspect ratio lock included.",
    badge: "Any format in",
    category: "webp" as CategoryId,
  },
  {
    href: "/heic-to-webp",
    name: "HEIC → WebP",
    shortName: "HEIC to WebP Converter",
    description: "Convert iPhone HEIC photos to WebP. Works in Chrome and Firefox via WebAssembly.",
    badge: "Cross-browser",
    category: "webp" as CategoryId,
  },
  {
    href: "/html-to-pdf",
    name: "HTML → PDF",
    shortName: "HTML to PDF Converter",
    description: "Convert HTML files to PDF in your browser. Drop any .html file for a private, instant, no-upload conversion.",
    badge: "No upload",
    category: "pdf" as CategoryId,
  },
  {
    href: "/jpg-to-pdf",
    name: "JPG → PDF",
    shortName: "JPG to PDF Converter",
    description: "Convert JPEG photos to PDF in your browser. Each image becomes a perfectly sized page.",
    badge: "Lossless pages",
    category: "pdf" as CategoryId,
  },
  {
    href: "/png-to-pdf",
    name: "PNG → PDF",
    shortName: "PNG to PDF Converter",
    description: "Convert PNG images to PDF instantly. Preserves detail and supports transparent backgrounds.",
    badge: "Alpha safe",
    category: "pdf" as CategoryId,
  },
  {
    href: "/webp-to-pdf",
    name: "WebP → PDF",
    shortName: "WebP to PDF Converter",
    description: "Convert WebP images to PDF format for sharing, printing, or archiving.",
    badge: "Modern format",
    category: "pdf" as CategoryId,
  },
  {
    href: "/heic-to-pdf",
    name: "HEIC → PDF",
    shortName: "HEIC to PDF Converter",
    description: "Convert iPhone HEIC photos directly to PDF. No cloud upload, works in Chrome and Firefox.",
    badge: "iPhone photos",
    category: "pdf" as CategoryId,
  },
  {
    href: "/bmp-to-pdf",
    name: "BMP → PDF",
    shortName: "BMP to PDF Converter",
    description: "Convert uncompressed BMP files to PDF. Instantly shrink file size while preserving detail.",
    badge: "Uncompressed in",
    category: "pdf" as CategoryId,
  },
  {
    href: "/tiff-to-pdf",
    name: "TIFF → PDF",
    shortName: "TIFF to PDF Converter",
    description: "Convert high-resolution TIFF images to PDF for easy sharing and printing.",
    badge: "High-res source",
    category: "pdf" as CategoryId,
  },
  {
    href: "/gif-to-pdf",
    name: "GIF → PDF",
    shortName: "GIF to PDF Converter",
    description: "Convert GIF images to PDF. Extracts the first frame for a clean static page.",
    badge: "Static frame",
    category: "pdf" as CategoryId,
  },
  {
    href: "/svg-to-pdf",
    name: "SVG → PDF",
    shortName: "SVG to PDF Converter",
    description: "Rasterize SVG vector graphics to PDF. Choose your output dimensions for crisp results.",
    badge: "Vector to PDF",
    category: "pdf" as CategoryId,
  },
  {
    href: "/avif-to-pdf",
    name: "AVIF → PDF",
    shortName: "AVIF to PDF Converter",
    description: "Convert AVIF images to PDF for broader compatibility with document workflows.",
    badge: "Modern format",
    category: "pdf" as CategoryId,
  },
  {
    href: "/ico-to-pdf",
    name: "ICO → PDF",
    shortName: "ICO to PDF Converter",
    description: "Extract and convert ICO icon files to PDF. Useful for documenting icon sets.",
    badge: "Icon extract",
    category: "pdf" as CategoryId,
  },
  {
    href: "/jfif-to-pdf",
    name: "JFIF → PDF",
    shortName: "JFIF to PDF Converter",
    description: "Convert JFIF photos to PDF. JFIF is a JPEG variant — full quality preserved in the output.",
    badge: "JPEG variant",
    category: "pdf" as CategoryId,
  },
] as const;

export type Tool = (typeof TOOLS)[number];
