export const CATEGORIES = [
  { id: "all", label: "All" },
  { id: "webp", label: "WebP Tools" },
  { id: "pdf", label: "Image to PDF" },
  { id: "pdf-tools", label: "PDF Tools" },
  { id: "qr", label: "QR Codes" },
  { id: "image-tools", label: "Image Tools" },
] as const;

export type CategoryId = (typeof CATEGORIES)[number]["id"];

export const TOOLS = [
  {
    href: "/tools/png-to-webp",
    name: "PNG to WebP",
    shortName: "PNG to WebP Converter",
    description: "Convert PNG images to WebP format. Dramatically smaller files at the same visual quality.",
    badge: "Lossless source",
    category: "webp" as CategoryId,
  },
  {
    href: "/tools/jpg-to-webp",
    name: "JPG to WebP",
    shortName: "JPG to WebP Converter",
    description: "Convert JPEG photos to WebP. Up to 34% smaller than JPEG at comparable quality.",
    badge: "Lossy optimized",
    category: "webp" as CategoryId,
  },
  {
    href: "/tools/gif-to-webp",
    name: "GIF to WebP",
    shortName: "GIF to WebP Converter",
    description: "Convert GIF images to WebP for smaller static frames and more efficient compression.",
    badge: "Static frame",
    category: "webp" as CategoryId,
  },
  {
    href: "/tools/avif-to-webp",
    name: "AVIF to WebP",
    shortName: "AVIF to WebP Converter",
    description: "Convert AVIF images to WebP for broader browser compatibility. No upload required.",
    badge: "Modern format",
    category: "webp" as CategoryId,
  },
  {
    href: "/tools/bmp-to-webp",
    name: "BMP to WebP",
    shortName: "BMP to WebP Converter",
    description: "Convert uncompressed BMP files to WebP. Achieve massive size reduction instantly.",
    badge: "Uncompressed in",
    category: "webp" as CategoryId,
  },
  {
    href: "/tools/tiff-to-webp",
    name: "TIFF to WebP",
    shortName: "TIFF to WebP Converter",
    description: "Convert high-resolution TIFF images to lightweight WebP for web use.",
    badge: "High-res source",
    category: "webp" as CategoryId,
  },
  {
    href: "/tools/svg-to-webp",
    name: "SVG to WebP",
    shortName: "SVG to WebP Converter",
    description: "Rasterize SVG vector graphics to WebP. Crisp output at your chosen quality.",
    badge: "Vector to raster",
    category: "webp" as CategoryId,
  },
  {
    href: "/tools/ico-to-webp",
    name: "ICO to WebP",
    shortName: "ICO to WebP Converter",
    description: "Extract and convert ICO icon files to WebP. Great for repurposing favicons.",
    badge: "Icon extract",
    category: "webp" as CategoryId,
  },
  {
    href: "/tools/jfif-to-webp",
    name: "JFIF to WebP",
    shortName: "JFIF to WebP Converter",
    description: "Convert JFIF photos to WebP. JFIF is a JPEG variant — get up to 34% smaller files.",
    badge: "JPEG variant",
    category: "webp" as CategoryId,
  },
  {
    href: "/tools/pdf-to-webp",
    name: "PDF to WebP",
    shortName: "PDF to WebP Converter",
    description: "Convert the first page of a PDF document to a WebP image for thumbnails and previews.",
    badge: "First page",
    category: "webp" as CategoryId,
  },
  {
    href: "/tools/webp-to-webp",
    name: "WebP Re-optimize",
    shortName: "WebP Re-optimizer",
    description: "Re-compress an existing WebP file at a different quality level to fine-tune file size.",
    badge: "Re-compress",
    category: "webp" as CategoryId,
  },
  {
    href: "/tools/webp-resizer",
    name: "WebP Resizer",
    shortName: "Image to WebP Resizer",
    description: "Resize any image to custom dimensions and export as WebP. Aspect ratio lock included.",
    badge: "Any format in",
    category: "webp" as CategoryId,
  },
  {
    href: "/tools/heic-to-webp",
    name: "HEIC to WebP",
    shortName: "HEIC to WebP Converter",
    description: "Convert iPhone HEIC photos to WebP. Works in Chrome and Firefox via WebAssembly.",
    badge: "Cross-browser",
    category: "webp" as CategoryId,
  },
  {
    href: "/tools/html-to-pdf",
    name: "HTML to PDF",
    shortName: "HTML to PDF Converter",
    description: "Convert HTML files to PDF in your browser. Drop any .html file for a private, instant, no-upload conversion.",
    badge: "No upload",
    category: "pdf" as CategoryId,
  },
  {
    href: "/tools/jpg-to-pdf",
    name: "JPG to PDF",
    shortName: "JPG to PDF Converter",
    description: "Convert JPEG photos to PDF in your browser. Each image becomes a perfectly sized page.",
    badge: "Lossless pages",
    category: "pdf" as CategoryId,
  },
  {
    href: "/tools/png-to-pdf",
    name: "PNG to PDF",
    shortName: "PNG to PDF Converter",
    description: "Convert PNG images to PDF instantly. Preserves detail and supports transparent backgrounds.",
    badge: "Alpha safe",
    category: "pdf" as CategoryId,
  },
  {
    href: "/tools/webp-to-pdf",
    name: "WebP to PDF",
    shortName: "WebP to PDF Converter",
    description: "Convert WebP images to PDF format for sharing, printing, or archiving.",
    badge: "Modern format",
    category: "pdf" as CategoryId,
  },
  {
    href: "/tools/heic-to-pdf",
    name: "HEIC to PDF",
    shortName: "HEIC to PDF Converter",
    description: "Convert iPhone HEIC photos directly to PDF. No cloud upload, works in Chrome and Firefox.",
    badge: "iPhone photos",
    category: "pdf" as CategoryId,
  },
  {
    href: "/tools/bmp-to-pdf",
    name: "BMP to PDF",
    shortName: "BMP to PDF Converter",
    description: "Convert uncompressed BMP files to PDF. Instantly shrink file size while preserving detail.",
    badge: "Uncompressed in",
    category: "pdf" as CategoryId,
  },
  {
    href: "/tools/tiff-to-pdf",
    name: "TIFF to PDF",
    shortName: "TIFF to PDF Converter",
    description: "Convert high-resolution TIFF images to PDF for easy sharing and printing.",
    badge: "High-res source",
    category: "pdf" as CategoryId,
  },
  {
    href: "/tools/gif-to-pdf",
    name: "GIF to PDF",
    shortName: "GIF to PDF Converter",
    description: "Convert GIF images to PDF. Extracts the first frame for a clean static page.",
    badge: "Static frame",
    category: "pdf" as CategoryId,
  },
  {
    href: "/tools/svg-to-pdf",
    name: "SVG to PDF",
    shortName: "SVG to PDF Converter",
    description: "Rasterize SVG vector graphics to PDF. Choose your output dimensions for crisp results.",
    badge: "Vector to PDF",
    category: "pdf" as CategoryId,
  },
  {
    href: "/tools/avif-to-pdf",
    name: "AVIF to PDF",
    shortName: "AVIF to PDF Converter",
    description: "Convert AVIF images to PDF for broader compatibility with document workflows.",
    badge: "Modern format",
    category: "pdf" as CategoryId,
  },
  {
    href: "/tools/ico-to-pdf",
    name: "ICO to PDF",
    shortName: "ICO to PDF Converter",
    description: "Extract and convert ICO icon files to PDF. Useful for documenting icon sets.",
    badge: "Icon extract",
    category: "pdf" as CategoryId,
  },
  {
    href: "/tools/jfif-to-pdf",
    name: "JFIF to PDF",
    shortName: "JFIF to PDF Converter",
    description: "Convert JFIF photos to PDF. JFIF is a JPEG variant — full quality preserved in the output.",
    badge: "JPEG variant",
    category: "pdf" as CategoryId,
  },
  {
    href: "/tools/merge-pdf",
    name: "Merge PDF",
    shortName: "PDF Merger",
    description: "Combine multiple PDF files into one document. Drag in any number of PDFs, set the order, and download.",
    badge: "Combine",
    category: "pdf-tools" as CategoryId,
  },
  {
    href: "/tools/split-pdf",
    name: "Split PDF",
    shortName: "PDF Splitter",
    description: "Split a PDF into individual pages or custom ranges. Download all parts as a ZIP file.",
    badge: "Extract pages",
    category: "pdf-tools" as CategoryId,
  },
  {
    href: "/tools/rotate-pdf",
    name: "Rotate PDF",
    shortName: "PDF Page Rotator",
    description: "Rotate all pages or specific pages in a PDF by 90°, 180°, or 270°. No upload needed.",
    badge: "Fix orientation",
    category: "pdf-tools" as CategoryId,
  },
  {
    href: "/tools/protect-pdf",
    name: "Protect PDF",
    shortName: "PDF Password Protector",
    description: "Add a password to a PDF to prevent unauthorised access. Encryption applied entirely in-browser.",
    badge: "Encrypt",
    category: "pdf-tools" as CategoryId,
  },
  {
    href: "/tools/unlock-pdf",
    name: "Unlock PDF",
    shortName: "PDF Password Remover",
    description: "Remove the password from a PDF file. Enter the current password and download an unlocked copy.",
    badge: "Remove lock",
    category: "pdf-tools" as CategoryId,
  },
  {
    href: "/tools/watermark-pdf",
    name: "Watermark PDF",
    shortName: "PDF Watermark Tool",
    description: "Stamp a custom text watermark on every page of a PDF. Choose position, opacity, and font size.",
    badge: "Add stamp",
    category: "pdf-tools" as CategoryId,
  },
  {
    href: "/tools/pdf-page-numbers",
    name: "PDF Page Numbers",
    shortName: "Add Page Numbers to PDF",
    description: "Add page numbers to every page of a PDF. Choose position, format, and starting number.",
    badge: "Numbering",
    category: "pdf-tools" as CategoryId,
  },
  {
    href: "/tools/crop-pdf",
    name: "Crop PDF",
    shortName: "PDF Margin Cropper",
    description: "Trim margins from every page of a PDF by adjusting the CropBox. Enter values in points.",
    badge: "Trim margins",
    category: "pdf-tools" as CategoryId,
  },
  {
    href: "/tools/rearrange-pdf",
    name: "Manage PDF Pages",
    shortName: "Rearrange & Remove PDF Pages",
    description: "Drag to reorder pages and click to remove them. See all pages as thumbnails in one view.",
    badge: "Reorder & remove",
    category: "pdf-tools" as CategoryId,
  },
  {
    href: "/tools/pdf-to-images",
    name: "PDF to Images",
    shortName: "PDF to JPG / PNG / WebP",
    description: "Convert every page of a PDF to a JPG, PNG, or WebP image. Download as a ZIP file.",
    badge: "All pages",
    category: "pdf-tools" as CategoryId,
  },
  {
    href: "/tools/sign-pdf",
    name: "Sign PDF",
    shortName: "PDF Signature Tool",
    description: "Draw or type your signature and embed it on any page of a PDF. Free, private, no upload.",
    badge: "E-signature",
    category: "pdf-tools" as CategoryId,
  },
  {
    href: "/tools/ocr-pdf",
    name: "OCR PDF",
    shortName: "Extract Text from PDF",
    description: "Extract text from scanned or image-based PDFs using OCR. Supports 6 languages.",
    badge: "Scan to text",
    category: "pdf-tools" as CategoryId,
  },
  {
    href: "/tools/edit-pdf",
    name: "Edit PDF",
    shortName: "PDF Annotation Editor",
    description: "Add text, shapes, highlights, and drawings to any PDF page. White-out to cover content.",
    badge: "Annotate",
    category: "pdf-tools" as CategoryId,
  },
  {
    href: "/tools/compare-pdf",
    name: "Compare PDF",
    shortName: "PDF Side-by-Side Viewer",
    description: "View two PDF files side by side, page by page. Spot differences between versions visually.",
    badge: "Side by side",
    category: "pdf-tools" as CategoryId,
  },
  {
    href: "/tools/qr-code-generator",
    name: "QR Code Generator",
    shortName: "QR Code Generator",
    description: "Generate QR codes for URLs, text, WiFi, email, phone, and contacts. Download as PNG or SVG.",
    badge: "Free",
    category: "qr" as CategoryId,
  },
  {
    href: "/tools/qr-code-reader",
    name: "QR Code Reader",
    shortName: "QR Code Scanner & Decoder",
    description: "Upload an image to decode any QR code instantly. No camera required — works with screenshots too.",
    badge: "Instant decode",
    category: "qr" as CategoryId,
  },
  {
    href: "/tools/qr-code-with-logo",
    name: "QR Code with Logo",
    shortName: "QR Code Generator with Logo",
    description: "Generate a QR code with your logo or image embedded in the centre. Download as PNG.",
    badge: "Custom logo",
    category: "qr" as CategoryId,
  },
  {
    href: "/tools/batch-qr-generator",
    name: "Batch QR Generator",
    shortName: "Bulk QR Code Generator",
    description: "Paste a list of URLs or text — generate hundreds of QR codes at once and download as a ZIP.",
    badge: "Bulk export",
    category: "qr" as CategoryId,
  },
  {
    href: "/tools/image-compressor",
    name: "Image Compressor",
    shortName: "Image Compressor",
    description: "Compress JPEG, PNG, and WebP images with a quality slider. See size savings before downloading.",
    badge: "Lossy & lossless",
    category: "image-tools" as CategoryId,
  },
  {
    href: "/tools/image-cropper",
    name: "Image Cropper",
    shortName: "Free Image Cropper",
    description: "Crop any image to a custom area or preset ratio — 1:1, 16:9, 4:3, and more. Export as PNG.",
    badge: "Preset ratios",
    category: "image-tools" as CategoryId,
  },
  {
    href: "/tools/background-remover",
    name: "Background Remover",
    shortName: "Remove Image Background",
    description: "Remove the background from any photo using AI — runs entirely in your browser, no upload needed.",
    badge: "AI-powered",
    category: "image-tools" as CategoryId,
  },
  {
    href: "/tools/favicon-generator",
    name: "Favicon Generator",
    shortName: "Favicon Generator",
    description: "Upload any image and download a complete favicon set: ICO, 16×16, 32×32, 48×48, 64×64, 128×128, 256×256 PNG.",
    badge: "Multi-size ZIP",
    category: "image-tools" as CategoryId,
  },
  {
    href: "/tools/image-flip-rotate",
    name: "Flip & Rotate",
    shortName: "Image Flip & Rotate",
    description: "Flip images horizontally or vertically and rotate by 90°, 180°, or 270°. Live preview, one-click download.",
    badge: "Non-destructive",
    category: "image-tools" as CategoryId,
  },
  {
    href: "/tools/photo-adjustments",
    name: "Photo Adjustments",
    shortName: "Photo Adjustments",
    description: "Adjust brightness, contrast, saturation, hue, blur, and sharpness with live preview. Includes one-click presets.",
    badge: "Live preview",
    category: "image-tools" as CategoryId,
  },
  {
    href: "/tools/image-watermark",
    name: "Image Watermark",
    shortName: "Image Watermark Tool",
    description: "Add a custom text watermark to any image. Control position, size, opacity, color, and font. Tiled mode included.",
    badge: "Text overlay",
    category: "image-tools" as CategoryId,
  },
  {
    href: "/tools/image-resizer",
    name: "Image Resizer",
    shortName: "Free Image Resizer",
    description: "Resize any image to exact pixel dimensions or a percentage scale. Aspect ratio lock and quick presets included.",
    badge: "Any format",
    category: "image-tools" as CategoryId,
  },
  {
    href: "/tools/rounded-corners",
    name: "Rounded Corners",
    shortName: "Rounded Corners Tool",
    description: "Add rounded corners to any image with a radius slider. Per-corner control available. Exports as PNG with transparency.",
    badge: "Transparent PNG",
    category: "image-tools" as CategoryId,
  },
  {
    href: "/tools/color-palette",
    name: "Color Palette",
    shortName: "Color Palette Extractor",
    description: "Extract 8 dominant colors from any image. Copy as HEX, RGB, or HSL. Export a palette PNG swatch sheet.",
    badge: "8 colors",
    category: "image-tools" as CategoryId,
  },
  {
    href: "/tools/image-border",
    name: "Add Border",
    shortName: "Image Border Tool",
    description: "Add a solid, gradient, or blurred photo-style border to any image. Adjustable width and colors.",
    badge: "3 styles",
    category: "image-tools" as CategoryId,
  },
  {
    href: "/tools/image-collage",
    name: "Image Collage",
    shortName: "Image Collage Maker",
    description: "Combine 2 to 6 photos into a grid collage. Six layout options, custom gap, and background color.",
    badge: "Grid layouts",
    category: "image-tools" as CategoryId,
  },
  {
    href: "/tools/grayscale-tint",
    name: "Grayscale & Tint",
    shortName: "Grayscale, Sepia & Duotone",
    description: "Apply B&W, sepia, warm, cool, faded, or duotone effects with adjustable intensity and live preview.",
    badge: "6 effects",
    category: "image-tools" as CategoryId,
  },
] as const;

export type Tool = (typeof TOOLS)[number];
