export const CATEGORIES = [
  { id: "all", label: "All" },
  { id: "webp", label: "WebP Tools" },
  { id: "pdf", label: "Image to PDF" },
  { id: "pdf-tools", label: "PDF Tools" },
  { id: "qr", label: "QR Codes" },
  { id: "image-tools", label: "Image Tools" },
  { id: "color-tools", label: "Color Tools" },
  { id: "text-tools", label: "Text Tools" },
  { id: "dev-tools", label: "Developer Tools" },
  { id: "unit-converter", label: "Unit Converter" },
  { id: "calculators", label: "Calculators" },
  { id: "math-tools", label: "Math Tools" },
  { id: "finance", label: "Finance" },
  { id: "health-fitness", label: "Health & Fitness" },
  { id: "cooking", label: "Cooking" },
] as const;

export type CategoryId = (typeof CATEGORIES)[number]["id"];

export const TOOLS = [
  {
    href: "/tools/png-to-webp",
    name: "PNG to WebP",
    shortName: "PNG to WebP Converter",
    description: "Convert PNG images to WebP format. Dramatically smaller files at the same visual quality.",
    badge: "Lossless source",
    category: "webp" as CategoryId,
  },
  {
    href: "/tools/jpg-to-webp",
    name: "JPG to WebP",
    shortName: "JPG to WebP Converter",
    description: "Convert JPEG photos to WebP. Up to 34% smaller than JPEG at comparable quality.",
    badge: "Lossy optimized",
    category: "webp" as CategoryId,
  },
  {
    href: "/tools/gif-to-webp",
    name: "GIF to WebP",
    shortName: "GIF to WebP Converter",
    description: "Convert GIF images to WebP for smaller static frames and more efficient compression.",
    badge: "Static frame",
    category: "webp" as CategoryId,
  },
  {
    href: "/tools/avif-to-webp",
    name: "AVIF to WebP",
    shortName: "AVIF to WebP Converter",
    description: "Convert AVIF images to WebP for broader browser compatibility. No upload required.",
    badge: "Modern format",
    category: "webp" as CategoryId,
  },
  {
    href: "/tools/bmp-to-webp",
    name: "BMP to WebP",
    shortName: "BMP to WebP Converter",
    description: "Convert uncompressed BMP files to WebP. Achieve massive size reduction instantly.",
    badge: "Uncompressed in",
    category: "webp" as CategoryId,
  },
  {
    href: "/tools/tiff-to-webp",
    name: "TIFF to WebP",
    shortName: "TIFF to WebP Converter",
    description: "Convert high-resolution TIFF images to lightweight WebP for web use.",
    badge: "High-res source",
    category: "webp" as CategoryId,
  },
  {
    href: "/tools/svg-to-webp",
    name: "SVG to WebP",
    shortName: "SVG to WebP Converter",
    description: "Rasterize SVG vector graphics to WebP. Crisp output at your chosen quality.",
    badge: "Vector to raster",
    category: "webp" as CategoryId,
  },
  {
    href: "/tools/ico-to-webp",
    name: "ICO to WebP",
    shortName: "ICO to WebP Converter",
    description: "Extract and convert ICO icon files to WebP. Great for repurposing favicons.",
    badge: "Icon extract",
    category: "webp" as CategoryId,
  },
  {
    href: "/tools/jfif-to-webp",
    name: "JFIF to WebP",
    shortName: "JFIF to WebP Converter",
    description: "Convert JFIF photos to WebP. JFIF is a JPEG variant | get up to 34% smaller files.",
    badge: "JPEG variant",
    category: "webp" as CategoryId,
  },
  {
    href: "/tools/pdf-to-webp",
    name: "PDF to WebP",
    shortName: "PDF to WebP Converter",
    description: "Convert the first page of a PDF document to a WebP image for thumbnails and previews.",
    badge: "First page",
    category: "webp" as CategoryId,
  },
  {
    href: "/tools/webp-to-webp",
    name: "WebP Re-optimize",
    shortName: "WebP Re-optimizer",
    description: "Re-compress an existing WebP file at a different quality level to fine-tune file size.",
    badge: "Re-compress",
    category: "webp" as CategoryId,
  },
  {
    href: "/tools/webp-resizer",
    name: "WebP Resizer",
    shortName: "Image to WebP Resizer",
    description: "Resize any image to custom dimensions and export as WebP. Aspect ratio lock included.",
    badge: "Any format in",
    category: "webp" as CategoryId,
  },
  {
    href: "/tools/png-resizer",
    name: "PNG Resizer",
    shortName: "Image to PNG Resizer",
    description: "Resize any image to exact pixel dimensions and export as lossless PNG. Aspect ratio lock included.",
    badge: "Lossless out",
    category: "image-tools" as CategoryId,
  },
  {
    href: "/tools/jpg-resizer",
    name: "JPG Resizer",
    shortName: "Image to JPG Resizer",
    description: "Resize any image to exact pixel dimensions and export as JPG with adjustable quality. Universal format.",
    badge: "Compact out",
    category: "image-tools" as CategoryId,
  },
  {
    href: "/tools/heic-resizer",
    name: "HEIC Resizer",
    shortName: "HEIC Photo Resizer",
    description: "Resize iPhone HEIC and HEIF photos to custom dimensions and export as JPG. Works via WebAssembly, no upload.",
    badge: "iPhone photos",
    category: "webp" as CategoryId,
  },
  {
    href: "/tools/heic-to-webp",
    name: "HEIC to WebP",
    shortName: "HEIC to WebP Converter",
    description: "Convert iPhone HEIC photos to WebP. Works in Chrome and Firefox via WebAssembly.",
    badge: "Cross-browser",
    category: "webp" as CategoryId,
  },
  {
    href: "/tools/heic-to-png",
    name: "HEIC to PNG",
    shortName: "HEIC to PNG Converter",
    description: "Convert iPhone HEIC photos to PNG for lossless, fully compatible output. Works via WebAssembly, no upload.",
    badge: "Lossless out",
    category: "webp" as CategoryId,
  },
  {
    href: "/tools/heic-to-jpg",
    name: "HEIC to JPG",
    shortName: "HEIC to JPG Converter",
    description: "Convert iPhone HEIC photos to JPG with adjustable quality. Universal format, works everywhere.",
    badge: "Universal",
    category: "webp" as CategoryId,
  },
  {
    href: "/tools/html-to-pdf",
    name: "HTML to PDF",
    shortName: "HTML to PDF Converter",
    description: "Convert HTML files to PDF in your browser. Drop any .html file for a private, instant, no-upload conversion.",
    badge: "No upload",
    category: "pdf" as CategoryId,
  },
  {
    href: "/tools/jpg-to-pdf",
    name: "JPG to PDF",
    shortName: "JPG to PDF Converter",
    description: "Convert JPEG photos to PDF in your browser. Each image becomes a perfectly sized page.",
    badge: "Lossless pages",
    category: "pdf" as CategoryId,
  },
  {
    href: "/tools/png-to-pdf",
    name: "PNG to PDF",
    shortName: "PNG to PDF Converter",
    description: "Convert PNG images to PDF instantly. Preserves detail and supports transparent backgrounds.",
    badge: "Alpha safe",
    category: "pdf" as CategoryId,
  },
  {
    href: "/tools/webp-to-pdf",
    name: "WebP to PDF",
    shortName: "WebP to PDF Converter",
    description: "Convert WebP images to PDF format for sharing, printing, or archiving.",
    badge: "Modern format",
    category: "pdf" as CategoryId,
  },
  {
    href: "/tools/heic-to-pdf",
    name: "HEIC to PDF",
    shortName: "HEIC to PDF Converter",
    description: "Convert iPhone HEIC photos directly to PDF. No cloud upload, works in Chrome and Firefox.",
    badge: "iPhone photos",
    category: "pdf" as CategoryId,
  },
  {
    href: "/tools/bmp-to-pdf",
    name: "BMP to PDF",
    shortName: "BMP to PDF Converter",
    description: "Convert uncompressed BMP files to PDF. Instantly shrink file size while preserving detail.",
    badge: "Uncompressed in",
    category: "pdf" as CategoryId,
  },
  {
    href: "/tools/tiff-to-pdf",
    name: "TIFF to PDF",
    shortName: "TIFF to PDF Converter",
    description: "Convert high-resolution TIFF images to PDF for easy sharing and printing.",
    badge: "High-res source",
    category: "pdf" as CategoryId,
  },
  {
    href: "/tools/gif-to-pdf",
    name: "GIF to PDF",
    shortName: "GIF to PDF Converter",
    description: "Convert GIF images to PDF. Extracts the first frame for a clean static page.",
    badge: "Static frame",
    category: "pdf" as CategoryId,
  },
  {
    href: "/tools/svg-to-pdf",
    name: "SVG to PDF",
    shortName: "SVG to PDF Converter",
    description: "Rasterize SVG vector graphics to PDF. Choose your output dimensions for crisp results.",
    badge: "Vector to PDF",
    category: "pdf" as CategoryId,
  },
  {
    href: "/tools/avif-to-pdf",
    name: "AVIF to PDF",
    shortName: "AVIF to PDF Converter",
    description: "Convert AVIF images to PDF for broader compatibility with document workflows.",
    badge: "Modern format",
    category: "pdf" as CategoryId,
  },
  {
    href: "/tools/ico-to-pdf",
    name: "ICO to PDF",
    shortName: "ICO to PDF Converter",
    description: "Extract and convert ICO icon files to PDF. Useful for documenting icon sets.",
    badge: "Icon extract",
    category: "pdf" as CategoryId,
  },
  {
    href: "/tools/jfif-to-pdf",
    name: "JFIF to PDF",
    shortName: "JFIF to PDF Converter",
    description: "Convert JFIF photos to PDF. JFIF is a JPEG variant | full quality preserved in the output.",
    badge: "JPEG variant",
    category: "pdf" as CategoryId,
  },
  {
    href: "/tools/merge-pdf",
    name: "Merge PDF",
    shortName: "PDF Merger",
    description: "Combine multiple PDF files into one document. Drag in any number of PDFs, set the order, and download.",
    badge: "Combine",
    category: "pdf-tools" as CategoryId,
  },
  {
    href: "/tools/split-pdf",
    name: "Split PDF",
    shortName: "PDF Splitter",
    description: "Split a PDF into individual pages or custom ranges. Download all parts as a ZIP file.",
    badge: "Extract pages",
    category: "pdf-tools" as CategoryId,
  },
  {
    href: "/tools/rotate-pdf",
    name: "Rotate PDF",
    shortName: "PDF Page Rotator",
    description: "Rotate all pages or specific pages in a PDF by 90°, 180°, or 270°. No upload needed.",
    badge: "Fix orientation",
    category: "pdf-tools" as CategoryId,
  },
  {
    href: "/tools/protect-pdf",
    name: "Protect PDF",
    shortName: "PDF Password Protector",
    description: "Add a password to a PDF to prevent unauthorised access. Encryption applied entirely in-browser.",
    badge: "Encrypt",
    category: "pdf-tools" as CategoryId,
  },
  {
    href: "/tools/unlock-pdf",
    name: "Unlock PDF",
    shortName: "PDF Password Remover",
    description: "Remove the password from a PDF file. Enter the current password and download an unlocked copy.",
    badge: "Remove lock",
    category: "pdf-tools" as CategoryId,
  },
  {
    href: "/tools/watermark-pdf",
    name: "Watermark PDF",
    shortName: "PDF Watermark Tool",
    description: "Stamp a custom text watermark on every page of a PDF. Choose position, opacity, and font size.",
    badge: "Add stamp",
    category: "pdf-tools" as CategoryId,
  },
  {
    href: "/tools/pdf-page-numbers",
    name: "PDF Page Numbers",
    shortName: "Add Page Numbers to PDF",
    description: "Add page numbers to every page of a PDF. Choose position, format, and starting number.",
    badge: "Numbering",
    category: "pdf-tools" as CategoryId,
  },
  {
    href: "/tools/crop-pdf",
    name: "Crop PDF",
    shortName: "PDF Margin Cropper",
    description: "Trim margins from every page of a PDF by adjusting the CropBox. Enter values in points.",
    badge: "Trim margins",
    category: "pdf-tools" as CategoryId,
  },
  {
    href: "/tools/rearrange-pdf",
    name: "Manage PDF Pages",
    shortName: "Rearrange & Remove PDF Pages",
    description: "Drag to reorder pages and click to remove them. See all pages as thumbnails in one view.",
    badge: "Reorder & remove",
    category: "pdf-tools" as CategoryId,
  },
  {
    href: "/tools/pdf-to-images",
    name: "PDF to Images",
    shortName: "PDF to JPG / PNG / WebP",
    description: "Convert every page of a PDF to a JPG, PNG, or WebP image. Download as a ZIP file.",
    badge: "All pages",
    category: "pdf-tools" as CategoryId,
  },
  {
    href: "/tools/sign-pdf",
    name: "Sign PDF",
    shortName: "PDF Signature Tool",
    description: "Draw or type your signature and embed it on any page of a PDF. Free, private, no upload.",
    badge: "E-signature",
    category: "pdf-tools" as CategoryId,
  },
  {
    href: "/tools/ocr-pdf",
    name: "OCR PDF",
    shortName: "Extract Text from PDF",
    description: "Extract text from scanned or image-based PDFs using OCR. Supports 6 languages.",
    badge: "Scan to text",
    category: "pdf-tools" as CategoryId,
  },
  {
    href: "/tools/edit-pdf",
    name: "Edit PDF",
    shortName: "PDF Annotation Editor",
    description: "Add text, shapes, highlights, and drawings to any PDF page. White-out to cover content.",
    badge: "Annotate",
    category: "pdf-tools" as CategoryId,
  },
  {
    href: "/tools/compare-pdf",
    name: "Compare PDF",
    shortName: "PDF Side-by-Side Viewer",
    description: "View two PDF files side by side, page by page. Spot differences between versions visually.",
    badge: "Side by side",
    category: "pdf-tools" as CategoryId,
  },
  {
    href: "/tools/qr-code-generator",
    name: "QR Code Generator",
    shortName: "QR Code Generator",
    description: "Generate QR codes for URLs, text, WiFi, email, phone, and contacts. Download as PNG or SVG.",
    badge: "Free",
    category: "qr" as CategoryId,
  },
  {
    href: "/tools/qr-code-reader",
    name: "QR Code Reader",
    shortName: "QR Code Scanner & Decoder",
    description: "Upload an image to decode any QR code instantly. No camera required | works with screenshots too.",
    badge: "Instant decode",
    category: "qr" as CategoryId,
  },
  {
    href: "/tools/qr-code-with-logo",
    name: "QR Code with Logo",
    shortName: "QR Code Generator with Logo",
    description: "Generate a QR code with your logo or image embedded in the centre. Download as PNG.",
    badge: "Custom logo",
    category: "qr" as CategoryId,
  },
  {
    href: "/tools/batch-qr-generator",
    name: "Batch QR Generator",
    shortName: "Bulk QR Code Generator",
    description: "Paste a list of URLs or text | generate hundreds of QR codes at once and download as a ZIP.",
    badge: "Bulk export",
    category: "qr" as CategoryId,
  },
  {
    href: "/tools/vcard-qr-generator",
    name: "vCard QR Generator",
    shortName: "vCard Business Card QR Code",
    description: "Generate a scannable QR code from your contact details — name, company, phone, email, address, and social links. Scan to save.",
    badge: "Contact card",
    category: "qr" as CategoryId,
  },
  {
    href: "/tools/image-compressor",
    name: "Image Compressor",
    shortName: "Image Compressor",
    description: "Compress JPEG, PNG, and WebP images with a quality slider. See size savings before downloading.",
    badge: "Lossy & lossless",
    category: "image-tools" as CategoryId,
  },
  {
    href: "/tools/image-cropper",
    name: "Image Cropper",
    shortName: "Free Image Cropper",
    description: "Crop any image to a custom area or preset ratio | 1:1, 16:9, 4:3, and more. Export as PNG.",
    badge: "Preset ratios",
    category: "image-tools" as CategoryId,
  },
  {
    href: "/tools/background-remover",
    name: "Background Remover",
    shortName: "Remove Image Background",
    description: "Remove the background from any photo using AI | runs entirely in your browser, no upload needed.",
    badge: "AI-powered",
    category: "image-tools" as CategoryId,
  },
  {
    href: "/tools/favicon-generator",
    name: "Favicon Generator",
    shortName: "Favicon Generator",
    description: "Upload any image and download a complete favicon set: ICO, 16×16, 32×32, 48×48, 64×64, 128×128, 256×256 PNG.",
    badge: "Multi-size ZIP",
    category: "image-tools" as CategoryId,
  },
  {
    href: "/tools/image-flip-rotate",
    name: "Flip & Rotate",
    shortName: "Image Flip & Rotate",
    description: "Flip images horizontally or vertically and rotate by 90°, 180°, or 270°. Live preview, one-click download.",
    badge: "Non-destructive",
    category: "image-tools" as CategoryId,
  },
  {
    href: "/tools/photo-adjustments",
    name: "Photo Adjustments",
    shortName: "Photo Adjustments",
    description: "Adjust brightness, contrast, saturation, hue, blur, and sharpness with live preview. Includes one-click presets.",
    badge: "Live preview",
    category: "image-tools" as CategoryId,
  },
  {
    href: "/tools/image-watermark",
    name: "Image Watermark",
    shortName: "Image Watermark Tool",
    description: "Add a custom text watermark to any image. Control position, size, opacity, color, and font. Tiled mode included.",
    badge: "Text overlay",
    category: "image-tools" as CategoryId,
  },
  {
    href: "/tools/image-resizer",
    name: "Image Resizer",
    shortName: "Free Image Resizer",
    description: "Resize any image to exact pixel dimensions or a percentage scale. Aspect ratio lock and quick presets included.",
    badge: "Any format",
    category: "image-tools" as CategoryId,
  },
  {
    href: "/tools/rounded-corners",
    name: "Rounded Corners",
    shortName: "Rounded Corners Tool",
    description: "Add rounded corners to any image with a radius slider. Per-corner control available. Exports as PNG with transparency.",
    badge: "Transparent PNG",
    category: "image-tools" as CategoryId,
  },
  {
    href: "/tools/color-palette",
    name: "Color Palette",
    shortName: "Color Palette Extractor",
    description: "Extract 8 dominant colors from any image. Copy as HEX, RGB, or HSL. Export a palette PNG swatch sheet.",
    badge: "8 colors",
    category: "image-tools" as CategoryId,
  },
  {
    href: "/tools/image-border",
    name: "Add Border",
    shortName: "Image Border Tool",
    description: "Add a solid, gradient, or blurred photo-style border to any image. Adjustable width and colors.",
    badge: "3 styles",
    category: "image-tools" as CategoryId,
  },
  {
    href: "/tools/image-collage",
    name: "Image Collage",
    shortName: "Image Collage Maker",
    description: "Combine 2 to 6 photos into a grid collage. Six layout options, custom gap, and background color.",
    badge: "Grid layouts",
    category: "image-tools" as CategoryId,
  },
  {
    href: "/tools/grayscale-tint",
    name: "Grayscale & Tint",
    shortName: "Grayscale, Sepia & Duotone",
    description: "Apply B&W, sepia, warm, cool, faded, or duotone effects with adjustable intensity and live preview.",
    badge: "6 effects",
    category: "image-tools" as CategoryId,
  },
  {
    href: "/tools/social-media-resizer",
    name: "Social Media Resizer",
    shortName: "Social Media Image Resizer",
    description: "Resize any image to exact social media dimensions | Instagram, Twitter, Facebook, LinkedIn, YouTube, and more.",
    badge: "10+ presets",
    category: "image-tools" as CategoryId,
  },
  {
    href: "/tools/image-padding",
    name: "Add Image Padding",
    shortName: "Image Canvas Padding Tool",
    description: "Expand the canvas of any image by adding padding on each side. Choose a solid color or transparent background.",
    badge: "Expand canvas",
    category: "image-tools" as CategoryId,
  },
  {
    href: "/tools/image-to-base64",
    name: "Image to Base64",
    shortName: "Image to Base64 Encoder",
    description: "Encode any image to a Base64 string or data URI | and decode Base64 back to an image. Instant, no upload.",
    badge: "Encode & decode",
    category: "image-tools" as CategoryId,
  },
  {
    href: "/tools/noise-grain",
    name: "Noise & Grain",
    shortName: "Add Noise & Film Grain to Image",
    description: "Add film grain, luminance noise, or color noise to any image with adjustable intensity and live preview.",
    badge: "3 grain types",
    category: "image-tools" as CategoryId,
  },
  {
    href: "/tools/color-picker",
    name: "Color Picker",
    shortName: "Color Picker Tool",
    description: "Pick any color and instantly get its HEX, RGB, HSL, and CMYK values. Copy with one click.",
    badge: "4 formats",
    category: "color-tools" as CategoryId,
  },
  {
    href: "/tools/gradient-generator",
    name: "Gradient Generator",
    shortName: "CSS Gradient Generator",
    description: "Build beautiful linear and radial CSS gradients visually. Add stops, adjust angles, and copy the CSS code.",
    badge: "Copy CSS",
    category: "color-tools" as CategoryId,
  },
  {
    href: "/tools/contrast-checker",
    name: "Contrast Checker",
    shortName: "WCAG Contrast Checker",
    description: "Check the contrast ratio between two colors. Get instant WCAG AA and AAA pass/fail results for accessibility.",
    badge: "WCAG 2.1",
    category: "color-tools" as CategoryId,
  },
  {
    href: "/tools/color-palette-generator",
    name: "Color Palette Generator",
    shortName: "Color Palette Generator",
    description: "Generate complementary, analogous, triadic, and tetradic color schemes from any base color.",
    badge: "4 schemes",
    category: "color-tools" as CategoryId,
  },
  {
    href: "/tools/tint-shade-generator",
    name: "Tint & Shade Generator",
    shortName: "Tint & Shade Scale Generator",
    description: "Generate a full scale of tints and shades from any base color | like Tailwind's 50–950 palette. Copy any swatch instantly.",
    badge: "10-step scale",
    category: "color-tools" as CategoryId,
  },
  {
    href: "/tools/color-blindness-simulator",
    name: "Color Blindness Simulator",
    shortName: "Color Blindness Simulator",
    description: "Preview how any color looks to people with deuteranopia, protanopia, tritanopia, and achromatopsia.",
    badge: "4 types",
    category: "color-tools" as CategoryId,
  },
  {
    href: "/tools/shadow-generator",
    name: "CSS Shadow Generator",
    shortName: "CSS Box & Text Shadow Generator",
    description: "Build box-shadow and text-shadow CSS rules visually with live preview. Copy the ready-to-use CSS instantly.",
    badge: "Copy CSS",
    category: "color-tools" as CategoryId,
  },
  {
    href: "/tools/random-color-generator",
    name: "Random Color Generator",
    shortName: "Random Color Generator",
    description: "Generate random colors and lock the ones you like to build a palette. Copy HEX, RGB, or HSL values instantly.",
    badge: "Lock & build",
    category: "color-tools" as CategoryId,
  },
  {
    href: "/tools/color-converter",
    name: "Color Converter",
    shortName: "Color Converter",
    description: "Convert between HEX, RGB, HSL, HSB, and CMYK instantly. Edit any field and all others update in real time.",
    badge: "5 formats",
    category: "color-tools" as CategoryId,
  },
  {
    href: "/tools/color-mixer",
    name: "Color Mixer",
    shortName: "Color Mixer",
    description: "Blend two colors at any ratio with a gradient preview. Get the mixed HEX, RGB, and HSL values instantly.",
    badge: "Blend & preview",
    category: "color-tools" as CategoryId,
  },
  {
    href: "/tools/color-name-finder",
    name: "Color Name Finder",
    shortName: "CSS Color Name Finder",
    description: "Enter any color and find the nearest CSS named color. Covers all 148 W3C named colors with similarity scoring.",
    badge: "148 names",
    category: "color-tools" as CategoryId,
  },
  {
    href: "/tools/image-color-picker",
    name: "Image Color Picker",
    shortName: "Pick Color from Image",
    description: "Upload any image and hover or click any pixel to extract its exact color as HEX, RGB, and HSL.",
    badge: "Pixel perfect",
    category: "color-tools" as CategoryId,
  },
  {
    href: "/tools/opacity-calculator",
    name: "Opacity Calculator",
    shortName: "Color Opacity Calculator",
    description: "Preview any color at different opacities over light and dark backgrounds. Copy the rgba() CSS value instantly.",
    badge: "RGBA output",
    category: "color-tools" as CategoryId,
  },
  {
    href: "/tools/lorem-ipsum",
    name: "Lorem Ipsum Generator",
    shortName: "Lorem Ipsum Generator",
    description: "Generate classic lorem ipsum placeholder text with a paragraph count slider. Shuffled on every click, copy instantly.",
    badge: "Instant copy",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/text-case-converter",
    name: "Text Case Converter",
    shortName: "Text Case Converter",
    description: "Convert text between UPPERCASE, lowercase, Title Case, sentence case, camelCase, snake_case, and kebab-case.",
    badge: "8 cases",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/word-counter",
    name: "Word Counter",
    shortName: "Word & Character Counter",
    description: "Count words, characters, sentences, and paragraphs. Get reading time, speaking time, and top keyword density.",
    badge: "Reading time",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/plagiarism-checker",
    name: "Plagiarism Checker",
    shortName: "Plagiarism Checker",
    description: "Check your content for plagiarism and duplicate phrases. Get exact match and partial match scores with a downloadable PDF report.",
    badge: "No word limit",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/fancy-text",
    name: "Fancy Text Generator",
    shortName: "Fancy Text Generator",
    description: "Convert text into 19 Unicode font styles — bold, italic, script, fraktur, bubble, small caps, upside down, and more. Copy any style instantly.",
    badge: "19 styles",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/bold-text-generator",
    name: "Bold Text Generator",
    shortName: "Bold Text Generator",
    description: "Generate Unicode bold text that works in Instagram bios, Twitter, Discord, and anywhere plain text appears — no formatting tags needed.",
    badge: "𝗕𝗼𝗹𝗱 output",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/italic-text-generator",
    name: "Italic Text Generator",
    shortName: "Italic Text Generator",
    description: "Generate Unicode italic and cursive text for Instagram bios, Twitter posts, Discord nicknames, and more — paste anywhere, no markdown needed.",
    badge: "𝘐𝘵𝘢𝘭𝘪𝘤 output",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/strikethrough-text",
    name: "Strikethrough Text Generator",
    shortName: "Strikethrough Text Generator",
    description: "Add Unicode strikethrough, underline, double strikethrough, or overline to any text. Works in Instagram, Twitter, Discord, WhatsApp, and more.",
    badge: "4 variants",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/stylish-name-generator",
    name: "Stylish Name Generator",
    shortName: "Stylish Name Generator",
    description: "Turn any name into a stylish Unicode username for Instagram, Discord, TikTok, and gaming profiles. 19 font styles plus 16 decorative border templates.",
    badge: "Unicode + borders",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/free-fire-name-generator",
    name: "Free Fire Name Generator",
    shortName: "Free Fire Name Generator",
    description: "Create stylish Garena Free Fire names with 19 Unicode font styles and 20 FF border templates — ꧁꧂ ༒ ☬ and more. Copy-paste ready.",
    badge: "FF borders",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/pubg-name-generator",
    name: "PUBG Name Generator",
    shortName: "PUBG / BGMI Name Generator",
    description: "Generate stylish PUBG Mobile and BGMI usernames with 19 Unicode font styles and elite border templates. Find your unique player name instantly.",
    badge: "BGMI ready",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/password-generator",
    name: "Password Generator",
    shortName: "Random Password Generator",
    description: "Generate strong random passwords with custom length and character sets — uppercase, lowercase, numbers, and symbols. Strength indicator included.",
    badge: "Crypto random",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/hashtag-generator",
    name: "Hashtag Generator",
    shortName: "Hashtag Generator for Instagram",
    description: "Generate relevant hashtags from any topic or description. Includes curated hashtag banks for Fitness, Food, Travel, Tech, Gaming, and more.",
    badge: "8 categories",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/reverse-text",
    name: "Reverse Text Generator",
    shortName: "Reverse Text Generator",
    description: "Reverse characters, words, or lines in any text. Great for puzzles, fun social media posts, and text manipulation tasks.",
    badge: "3 modes",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/text-repeater",
    name: "Text Repeater",
    shortName: "Text Repeater Tool",
    description: "Repeat any text up to 50 times with custom separators — none, space, new line, comma, or your own custom delimiter.",
    badge: "Custom separator",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/random-name-generator",
    name: "Random Name Generator",
    shortName: "Random Name Generator",
    description: "Generate random full names, usernames, fantasy names, and baby names. Filter by gender and generate up to 20 names at once.",
    badge: "4 categories",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/json-formatter",
    name: "JSON Formatter",
    shortName: "JSON Formatter & Validator",
    description: "Prettify, format, and minify JSON with one click. Validates your JSON and shows clear error messages for malformed input.",
    badge: "Prettify & minify",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/base64-text",
    name: "Base64 Encoder / Decoder",
    shortName: "Base64 Text Encoder Decoder",
    description: "Encode plain text to Base64 or decode Base64 strings back to text. Live conversion as you type, with error handling for invalid input.",
    badge: "Encode & decode",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/url-encoder",
    name: "URL Encoder / Decoder",
    shortName: "URL Encoder Decoder",
    description: "Encode special characters in URLs using encodeURIComponent or decode percent-encoded strings back to readable text. Instant, in-browser.",
    badge: "Percent encode",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/uuid-generator",
    name: "UUID Generator",
    shortName: "UUID v4 Generator",
    description: "Generate cryptographically random UUID v4 identifiers. Create up to 20 at once, copy individually or all at once.",
    badge: "Batch generate",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/diff-checker",
    name: "Diff Checker",
    shortName: "Text Diff Checker",
    description: "Compare two blocks of text and highlight added, removed, and unchanged lines. See a summary of exactly what changed between versions.",
    badge: "Line diff",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/leet-speak",
    name: "Leet Speak Generator",
    shortName: "Leet Speak Translator",
    description: "Convert text to leet speak (1337) at Basic, Medium, or Extreme substitution levels. Classic internet culture cipher for usernames and fun.",
    badge: "3 levels",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/morse-code",
    name: "Morse Code Converter",
    shortName: "Morse Code Translator",
    description: "Convert text to Morse code or decode Morse back to text. Includes a Web Audio API player to listen to the beeps in real time.",
    badge: "Audio playback",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/emoji-text",
    name: "Emoji Text Converter",
    shortName: "Emoji Text Generator",
    description: "Transform your text into fun emoji styles — regional indicator flags, clap beat, sparkle wrap, and fire mode. Copy any variant instantly.",
    badge: "4 styles",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/rot13",
    name: "ROT13 / Caesar Cipher",
    shortName: "ROT13 & Caesar Cipher Tool",
    description: "Encode or decode text with ROT13 or a custom Caesar cipher shift 1–25. Bidirectional — ROT13 is its own inverse.",
    badge: "Classic cipher",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/markdown-preview",
    name: "Markdown Preview",
    shortName: "Markdown Live Preview",
    description: "Paste Markdown and see a live rendered preview side by side. Supports headers, bold, italic, code blocks, lists, links, and blockquotes.",
    badge: "Live preview",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/html-encoder",
    name: "HTML Encoder / Decoder",
    shortName: "HTML Entity Encoder Decoder",
    description: "Encode special characters to HTML entities (&lt;, &gt;, &amp;) and decode them back. Essential for safely embedding HTML inside HTML.",
    badge: "Entity encode",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/regex-tester",
    name: "Regex Tester",
    shortName: "Regular Expression Tester",
    description: "Test regular expressions against sample text with live match highlighting. See match count, captured groups, and character indices. Supports all JS regex flags.",
    badge: "Live match",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/number-to-words",
    name: "Number to Words",
    shortName: "Number to Words Converter",
    description: "Convert any number up to one quadrillion into English words. Supports integers, decimals, negatives, and ordinal form. Great for cheques and legal documents.",
    badge: "Ordinal too",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/ascii-art",
    name: "ASCII Art Generator",
    shortName: "Text to ASCII Art Generator",
    description: "Convert any text into ASCII art using classic block character rendering. Choose from multiple character sets and adjust output width. Copy-paste anywhere.",
    badge: "4 char sets",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/char-frequency",
    name: "Character Frequency Counter",
    shortName: "Char Frequency Counter",
    description: "Count how often each character appears in your text. Sort by frequency or alphabet. Toggle case sensitivity and whitespace inclusion. Visual bar chart.",
    badge: "Visual chart",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/text-to-slug",
    name: "Text to Slug Converter",
    shortName: "Text to URL Slug",
    description: "Convert any text to a URL-friendly slug. Strips accents, punctuation, and special characters. Choose hyphens or underscores as separators.",
    badge: "Accent strip",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/readability-score",
    name: "Readability Score Checker",
    shortName: "Readability Score",
    description: "Analyse text readability with Flesch-Kincaid Grade Level, Reading Ease, Coleman-Liau, and Gunning Fog indices. Paste any text for an instant score.",
    badge: "4 indices",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/syllable-counter",
    name: "Syllable Counter",
    shortName: "Syllable Counter",
    description: "Count syllables in any word or block of text. Shows total syllable count, syllable breakdown per word, and average syllables per word.",
    badge: "Per word",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/reading-time",
    name: "Reading Time Estimator",
    shortName: "Reading Time",
    description: "Estimate how long it takes to read any text at slow, average, and fast reading speeds. Enter a word count or paste full text.",
    badge: "3 speeds",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/sentence-counter",
    name: "Sentence Counter",
    shortName: "Sentence Counter",
    description: "Count sentences in any text. Shows sentence count, average words per sentence, longest and shortest sentences, and paragraph count.",
    badge: "Detailed stats",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/text-to-speech",
    name: "Text to Speech",
    shortName: "Text to Speech",
    description: "Convert text to speech using your browser's built-in voices. Choose voice, adjust speed and pitch. Free, works offline — no audio sent anywhere.",
    badge: "Browser voices",
    category: "text-tools" as CategoryId,
  },
  {
    href: "/tools/csv-to-json",
    name: "CSV to JSON Converter",
    shortName: "CSV to JSON",
    description: "Paste CSV data and get a clean JSON array. Supports quoted fields, custom delimiters (comma, semicolon, tab), and optional header row mapping.",
    badge: "Header mapping",
    category: "dev-tools" as CategoryId,
  },
  {
    href: "/tools/json-to-csv",
    name: "JSON to CSV Converter",
    shortName: "JSON to CSV",
    description: "Convert a JSON array of objects to CSV. Auto-detects columns from all records, handles nested values gracefully, and copies output instantly.",
    badge: "Auto columns",
    category: "dev-tools" as CategoryId,
  },
  {
    href: "/tools/crontab-explainer",
    name: "Crontab Explainer",
    shortName: "Cron Expression Explainer",
    description: "Paste a cron expression and get a plain-English explanation of each field. Shows the next 5 scheduled run times with date and time.",
    badge: "Next run times",
    category: "dev-tools" as CategoryId,
  },
  {
    href: "/tools/unix-timestamp",
    name: "Unix Timestamp Converter",
    shortName: "Unix Timestamp Converter",
    description: "Convert Unix timestamps to human-readable dates and back. Shows UTC, local time, and ISO 8601 formats. Displays the current timestamp live.",
    badge: "Live current",
    category: "dev-tools" as CategoryId,
  },
  {
    href: "/tools/jwt-decoder",
    name: "JWT Decoder",
    shortName: "JWT Token Decoder",
    description: "Decode JWT tokens to inspect the header, payload, and claims as formatted JSON. Shows expiry status and algorithm. No signature verification needed.",
    badge: "Expiry check",
    category: "dev-tools" as CategoryId,
  },
  {
    href: "/tools/length-converter",
    name: "Length Converter",
    shortName: "Length Unit Converter",
    description: "Convert between millimetres, centimetres, metres, kilometres, inches, feet, yards, miles, and nautical miles instantly. Type in any unit.",
    badge: "9 units",
    category: "unit-converter" as CategoryId,
  },
  {
    href: "/tools/weight-converter",
    name: "Weight Converter",
    shortName: "Weight & Mass Converter",
    description: "Convert between milligrams, grams, kilograms, metric tonnes, ounces, pounds, stone, and US short tons. Type in any unit, see all conversions.",
    badge: "8 units",
    category: "unit-converter" as CategoryId,
  },
  {
    href: "/tools/temperature-converter",
    name: "Temperature Converter",
    shortName: "Temperature Unit Converter",
    description: "Convert between Celsius, Fahrenheit, Kelvin, and Rankine. Live update as you type in any field. Common reference temperatures shown.",
    badge: "4 scales",
    category: "unit-converter" as CategoryId,
  },
  {
    href: "/tools/speed-converter",
    name: "Speed Converter",
    shortName: "Speed Unit Converter",
    description: "Convert between m/s, km/h, mph, knots, ft/s, and Mach. Live update as you type in any unit. Common reference speeds shown.",
    badge: "6 units",
    category: "unit-converter" as CategoryId,
  },
  {
    href: "/tools/area-converter",
    name: "Area Converter",
    shortName: "Area Unit Converter",
    description: "Convert area between mm², cm², m², km², in², ft², yd², acres, and hectares instantly. Type in any unit to update all others.",
    badge: "9 units",
    category: "unit-converter" as CategoryId,
  },
  {
    href: "/tools/volume-converter",
    name: "Volume Converter",
    shortName: "Volume Unit Converter",
    description: "Convert volume between ml, litres, m³, cubic inches, cubic feet, US cups, fl oz, gallons, and pints. Live update, no conversion button.",
    badge: "11 units",
    category: "unit-converter" as CategoryId,
  },
  {
    href: "/tools/pressure-converter",
    name: "Pressure Converter",
    shortName: "Pressure Unit Converter",
    description: "Convert pressure between Pascal, kPa, MPa, bar, psi, atm, and mmHg (Torr). Type in any unit and see all others update instantly.",
    badge: "7 units",
    category: "unit-converter" as CategoryId,
  },
  {
    href: "/tools/energy-converter",
    name: "Energy Converter",
    shortName: "Energy Unit Converter",
    description: "Convert energy between joules, kilojoules, calories, kcal, watt-hours, kWh, BTU, and electron volts. Live update as you type.",
    badge: "8 units",
    category: "unit-converter" as CategoryId,
  },
  {
    href: "/tools/data-storage-converter",
    name: "Data Storage Converter",
    shortName: "Data Storage Converter",
    description: "Convert between bits, bytes, KB, MB, GB, TB, and PB (binary, base-2). See all conversions at once as you type any value.",
    badge: "7 units",
    category: "unit-converter" as CategoryId,
  },
  {
    href: "/tools/time-converter",
    name: "Time Converter",
    shortName: "Time Unit Converter",
    description: "Convert time between milliseconds, seconds, minutes, hours, days, weeks, months, and years. Instant live update in any field.",
    badge: "8 units",
    category: "unit-converter" as CategoryId,
  },
  {
    href: "/tools/angle-converter",
    name: "Angle Converter",
    shortName: "Angle Unit Converter",
    description: "Convert angles between degrees, radians, gradians, arcminutes, arcseconds, and full revolutions. Live update as you type.",
    badge: "6 units",
    category: "unit-converter" as CategoryId,
  },
  {
    href: "/tools/yaml-to-json",
    name: "YAML ↔ JSON Converter",
    shortName: "YAML to JSON Converter",
    description: "Convert between YAML and JSON in both directions. JSON to YAML is always complete; YAML to JSON handles standard config-file syntax.",
    badge: "Bidirectional",
    category: "dev-tools" as CategoryId,
  },
  {
    href: "/tools/xml-formatter",
    name: "XML Formatter",
    shortName: "XML Formatter & Prettifier",
    description: "Paste XML and get it formatted with consistent indentation. Validates syntax and shows clear error messages for malformed markup.",
    badge: "Validates XML",
    category: "dev-tools" as CategoryId,
  },
  {
    href: "/tools/string-escape",
    name: "String Escape / Unescape",
    shortName: "String Escape Unescape",
    description: "Escape or unescape strings for JavaScript, JSON, SQL, and regular expressions. Switch between modes instantly.",
    badge: "4 modes",
    category: "dev-tools" as CategoryId,
  },
  {
    href: "/tools/base-converter",
    name: "Number Base Converter",
    shortName: "Binary Hex Octal Converter",
    description: "Convert integers between binary (base 2), octal (base 8), decimal (base 10), and hexadecimal (base 16). Live update in all fields.",
    badge: "Bin/Oct/Dec/Hex",
    category: "dev-tools" as CategoryId,
  },
  {
    href: "/tools/hash-generator",
    name: "Hash Generator",
    shortName: "Hash Generator",
    description: "Generate SHA-1, SHA-256, and SHA-512 cryptographic hashes from any text input. Runs in-browser using the Web Crypto API — nothing is sent to a server.",
    badge: "SHA-1/256/512",
    category: "dev-tools" as CategoryId,
  },
  {
    href: "/tools/url-parser",
    name: "URL Parser",
    shortName: "URL Parser",
    description: "Break down any URL into its components: protocol, hostname, port, pathname, query parameters, and fragment. Paste a URL for an instant breakdown.",
    badge: "All components",
    category: "dev-tools" as CategoryId,
  },
  {
    href: "/tools/color-code-converter",
    name: "Color Code Converter",
    shortName: "Color Converter",
    description: "Convert colour codes between HEX, RGB, HSL, and CMYK instantly. Type in any format and all others update live. Includes a colour preview swatch.",
    badge: "HEX/RGB/HSL/CMYK",
    category: "dev-tools" as CategoryId,
  },
  {
    href: "/tools/html-minifier",
    name: "HTML Minifier",
    shortName: "HTML Minifier",
    description: "Minify HTML by removing whitespace, comments, and redundant attributes. Shows original vs compressed size and the percentage reduction achieved.",
    badge: "Size reduction",
    category: "dev-tools" as CategoryId,
  },
  {
    href: "/tools/markdown-to-html",
    name: "Markdown to HTML Converter",
    shortName: "Markdown to HTML",
    description: "Convert Markdown to HTML and preview the rendered output side by side. Supports headings, bold, italic, lists, links, images, code blocks, and blockquotes.",
    badge: "Live preview",
    category: "dev-tools" as CategoryId,
  },
  {
    href: "/tools/percentage-calculator",
    name: "Percentage Calculator",
    shortName: "Percentage Calculator",
    description: "Calculate X% of Y, find what percentage X is of Y, compute percentage change, and increase or decrease values by a percentage.",
    badge: "5 modes",
    category: "calculators" as CategoryId,
  },
  {
    href: "/tools/tip-calculator",
    name: "Tip Calculator",
    shortName: "Tip Calculator",
    description: "Enter a bill amount, choose a tip percentage, and split by any number of people. Shows tip amount, total bill, and per-person cost.",
    badge: "Bill splitter",
    category: "calculators" as CategoryId,
  },
  {
    href: "/tools/bmi-calculator",
    name: "BMI Calculator",
    shortName: "BMI Calculator",
    description: "Calculate your Body Mass Index from height and weight. Supports metric and imperial units. Shows BMI category and healthy weight range.",
    badge: "Metric & imperial",
    category: "calculators" as CategoryId,
  },
  {
    href: "/tools/compound-interest",
    name: "Compound Interest Calculator",
    shortName: "Compound Interest Calculator",
    description: "Calculate how investments grow with compound interest. Choose compounding frequency, enter rate and time, and see year-by-year growth.",
    badge: "Year-by-year",
    category: "calculators" as CategoryId,
  },
  {
    href: "/tools/loan-calculator",
    name: "Loan Calculator",
    shortName: "Loan Payment Calculator",
    description: "Calculate monthly loan payments, total interest paid, and view an amortization breakdown for any loan amount, rate, and term.",
    badge: "Amortization",
    category: "calculators" as CategoryId,
  },
  {
    href: "/tools/age-calculator",
    name: "Age Calculator",
    shortName: "Age Calculator",
    description: "Calculate your exact age in years, months, and days from your date of birth. Shows days until your next birthday and the day of the week you were born.",
    badge: "Exact age",
    category: "calculators" as CategoryId,
  },
  {
    href: "/tools/date-difference",
    name: "Date Difference Calculator",
    shortName: "Date Difference",
    description: "Calculate the exact difference between two dates in days, weeks, months, and years. Useful for deadlines, durations, and event planning.",
    badge: "Days & weeks",
    category: "calculators" as CategoryId,
  },
  {
    href: "/tools/discount-calculator",
    name: "Discount Calculator",
    shortName: "Discount Calculator",
    description: "Calculate the sale price after a percentage discount, or find what percentage discount was applied. Shows original price, discount amount, and final price.",
    badge: "Sale price",
    category: "calculators" as CategoryId,
  },
  {
    href: "/tools/sales-tax-calculator",
    name: "Sales Tax Calculator",
    shortName: "Sales Tax Calculator",
    description: "Add or remove sales tax from a price. Enter the pre-tax or post-tax amount and the tax rate to calculate the other value instantly.",
    badge: "Add & remove",
    category: "calculators" as CategoryId,
  },
  {
    href: "/tools/calorie-calculator",
    name: "Calorie Calculator (BMR & TDEE)",
    shortName: "Calorie Calculator",
    description: "Calculate your Basal Metabolic Rate (BMR) and Total Daily Energy Expenditure (TDEE) using the Mifflin-St Jeor equation. Shows calorie targets for weight goals.",
    badge: "BMR & TDEE",
    category: "calculators" as CategoryId,
  },
  {
    href: "/tools/fuel-cost-calculator",
    name: "Fuel Cost Calculator",
    shortName: "Fuel Cost Calculator",
    description: "Calculate the fuel cost of a road trip based on distance, vehicle fuel efficiency, and price per litre or gallon. Supports metric and imperial units.",
    badge: "Trip cost",
    category: "calculators" as CategoryId,
  },
  {
    href: "/tools/hours-calculator",
    name: "Hours Calculator",
    shortName: "Hours Calculator",
    description: "Calculate total hours worked between a start and end time. Subtract break time and see your hours in decimal and HH:MM format. Supports overnight shifts.",
    badge: "Overtime ready",
    category: "calculators" as CategoryId,
  },
  {
    href: "/tools/unit-price-calculator",
    name: "Unit Price Calculator",
    shortName: "Unit Price Calculator",
    description: "Compare the price per unit across multiple items to find the best deal. Enter price and quantity for up to three products — instantly highlights the cheapest option.",
    badge: "Best deal finder",
    category: "calculators" as CategoryId,
  },
  {
    href: "/tools/electricity-cost-calculator",
    name: "Electricity Cost Calculator",
    shortName: "Electricity Cost",
    description: "Calculate how much it costs to run any appliance. Enter wattage, daily usage hours, and your electricity rate to get hourly, daily, monthly, and annual costs.",
    badge: "Any appliance",
    category: "calculators" as CategoryId,
  },
  {
    href: "/tools/salary-calculator",
    name: "Salary Calculator",
    shortName: "Salary Calculator",
    description: "Convert between annual salary, monthly pay, weekly pay, and hourly wage. Accounts for working hours per week and weeks per year for accurate conversions.",
    badge: "Bidirectional",
    category: "calculators" as CategoryId,
  },
  {
    href: "/tools/margin-calculator",
    name: "Margin Calculator",
    shortName: "Margin & Markup",
    description: "Calculate profit margin, gross profit, and markup from cost and revenue. Enter any two values to compute the third. Essential for pricing and business planning.",
    badge: "3-way solver",
    category: "calculators" as CategoryId,
  },
  {
    href: "/tools/roi-calculator",
    name: "ROI Calculator",
    shortName: "ROI Calculator",
    description: "Calculate the return on investment for any investment. Enter initial cost, final value, and time period to get total ROI and annualised return rate.",
    badge: "Annualised rate",
    category: "calculators" as CategoryId,
  },
  {
    href: "/tools/savings-goal-calculator",
    name: "Savings Goal Calculator",
    shortName: "Savings Goal",
    description: "Find out how long it will take to reach a savings goal. Enter your target amount, current savings, monthly contribution, and interest rate.",
    badge: "Month-by-month",
    category: "calculators" as CategoryId,
  },
  {
    href: "/tools/gpa-calculator",
    name: "GPA Calculator",
    shortName: "GPA Calculator",
    description: "Calculate your weighted GPA by entering courses with letter grades and credit hours. Supports 4.0 scale. Add or remove courses dynamically.",
    badge: "Weighted GPA",
    category: "calculators" as CategoryId,
  },
  {
    href: "/tools/grade-calculator",
    name: "Grade Calculator",
    shortName: "Grade Calculator",
    description: "Calculate your current weighted grade, what score you need on the final exam to reach a target grade, and your overall course percentage.",
    badge: "Final exam needed",
    category: "calculators" as CategoryId,
  },
  {
    href: "/tools/speed-calculator",
    name: "Speed, Distance & Time Calculator",
    shortName: "Speed Calculator",
    description: "Solve for speed, distance, or time given any two values. Supports km/h, mph, m/s, and knots. Instantly calculates the missing value.",
    badge: "3-way solver",
    category: "calculators" as CategoryId,
  },
  {
    href: "/tools/paint-calculator",
    name: "Paint Calculator",
    shortName: "Paint Calculator",
    description: "Calculate how many litres or gallons of paint you need for a room. Enter wall dimensions, number of coats, and coverage rate per litre.",
    badge: "Room coverage",
    category: "calculators" as CategoryId,
  },
  {
    href: "/tools/concrete-calculator",
    name: "Concrete Calculator",
    shortName: "Concrete Calculator",
    description: "Calculate the volume of concrete needed for slabs, footings, and columns. Shows cubic metres and cubic feet, and the number of standard bags required.",
    badge: "Slabs & columns",
    category: "calculators" as CategoryId,
  },
  {
    href: "/tools/fraction-calculator",
    name: "Fraction Calculator",
    shortName: "Fraction Calculator",
    description: "Add, subtract, multiply, and divide fractions and mixed numbers. Shows the result as a simplified fraction and decimal. Step-by-step solution included.",
    badge: "Simplifies result",
    category: "math-tools" as CategoryId,
  },
  {
    href: "/tools/quadratic-formula",
    name: "Quadratic Formula Calculator",
    shortName: "Quadratic Formula",
    description: "Solve any quadratic equation ax² + bx + c = 0. Enter a, b, c to get real or complex roots, the discriminant, and the vertex of the parabola.",
    badge: "Complex roots",
    category: "math-tools" as CategoryId,
  },
  {
    href: "/tools/prime-factorization",
    name: "Prime Factorization Calculator",
    shortName: "Prime Factorization",
    description: "Find the prime factorization of any number. Shows all prime factors, their exponents, all divisors, and whether the number is prime.",
    badge: "All divisors",
    category: "math-tools" as CategoryId,
  },
  {
    href: "/tools/lcm-gcd-calculator",
    name: "LCM and GCD Calculator",
    shortName: "LCM & GCD",
    description: "Calculate the Least Common Multiple (LCM) and Greatest Common Divisor (GCD) of two or more numbers. Shows the prime factorization method.",
    badge: "Multiple numbers",
    category: "math-tools" as CategoryId,
  },
  {
    href: "/tools/scientific-notation",
    name: "Scientific Notation Converter",
    shortName: "Scientific Notation",
    description: "Convert numbers between standard decimal form and scientific notation. Works with very large and very small numbers. Bidirectional conversion.",
    badge: "Bidirectional",
    category: "math-tools" as CategoryId,
  },
  {
    href: "/tools/pythagorean-theorem",
    name: "Pythagorean Theorem Calculator",
    shortName: "Pythagorean Theorem",
    description: "Solve right triangles using the Pythagorean theorem. Enter any two sides to find the third — hypotenuse, adjacent, or opposite. Shows full working.",
    badge: "Any two sides",
    category: "math-tools" as CategoryId,
  },
  {
    href: "/tools/roman-numeral-converter",
    name: "Roman Numeral Converter",
    shortName: "Roman Numerals",
    description: "Convert between Arabic numbers and Roman numerals. Supports numbers from 1 to 3,999. Bidirectional — enter either format.",
    badge: "Bidirectional",
    category: "math-tools" as CategoryId,
  },
  {
    href: "/tools/fibonacci-generator",
    name: "Fibonacci Sequence Generator",
    shortName: "Fibonacci Generator",
    description: "Generate the Fibonacci sequence up to a specified number of terms. Find the nth Fibonacci number and see the ratio convergence to the golden ratio.",
    badge: "Golden ratio",
    category: "math-tools" as CategoryId,
  },
  {
    href: "/tools/fuel-converter",
    name: "Fuel Efficiency Converter",
    shortName: "Fuel Economy Converter",
    description: "Convert fuel efficiency between mpg (US), mpg (UK), km/L, and L/100km. Handles the inverse relationship between consumption and efficiency.",
    badge: "4 units",
    category: "unit-converter" as CategoryId,
  },
  // Finance tools
  {
    href: "/tools/mortgage-calculator",
    name: "Mortgage Calculator",
    shortName: "Mortgage Calculator",
    description: "Calculate monthly mortgage payments, total interest paid, and view an amortization schedule.",
    badge: "Amortization",
    category: "finance" as CategoryId,
  },
  {
    href: "/tools/break-even-calculator",
    name: "Break-Even Calculator",
    shortName: "Break-Even Calculator",
    description: "Find the break-even point in units and revenue given fixed costs, variable costs, and selling price.",
    badge: "Business math",
    category: "finance" as CategoryId,
  },
  {
    href: "/tools/vat-calculator",
    name: "VAT Calculator",
    shortName: "VAT / GST Calculator",
    description: "Add or remove VAT/GST from any price. Supports custom tax rates and common presets.",
    badge: "Add or remove",
    category: "finance" as CategoryId,
  },
  {
    href: "/tools/net-worth-calculator",
    name: "Net Worth Calculator",
    shortName: "Net Worth Calculator",
    description: "Calculate your net worth by listing assets and liabilities. See a clear breakdown of where you stand.",
    badge: "Assets − Liabilities",
    category: "finance" as CategoryId,
  },
  {
    href: "/tools/investment-calculator",
    name: "Investment Calculator",
    shortName: "Investment Growth Calculator",
    description: "Calculate the future value of a lump sum or regular contributions with compound interest.",
    badge: "Compound growth",
    category: "finance" as CategoryId,
  },
  {
    href: "/tools/budget-calculator",
    name: "Budget Calculator",
    shortName: "Monthly Budget Calculator",
    description: "Track income and expenses across categories to see how much you save each month.",
    badge: "Income vs expenses",
    category: "finance" as CategoryId,
  },
  // Health & Fitness tools
  {
    href: "/tools/ideal-weight-calculator",
    name: "Ideal Weight Calculator",
    shortName: "Ideal Body Weight Calculator",
    description: "Calculate ideal body weight using four medical formulas: Devine, Robinson, Miller, and Hamwi.",
    badge: "4 formulas",
    category: "health-fitness" as CategoryId,
  },
  {
    href: "/tools/body-fat-calculator",
    name: "Body Fat Calculator",
    shortName: "Body Fat Percentage Calculator",
    description: "Estimate body fat percentage using the US Navy method based on waist, neck, and height measurements.",
    badge: "Navy method",
    category: "health-fitness" as CategoryId,
  },
  {
    href: "/tools/heart-rate-zones",
    name: "Heart Rate Zones",
    shortName: "Heart Rate Zone Calculator",
    description: "Calculate your 5 training heart rate zones based on your maximum heart rate or age.",
    badge: "5 zones",
    category: "health-fitness" as CategoryId,
  },
  {
    href: "/tools/water-intake-calculator",
    name: "Water Intake Calculator",
    shortName: "Daily Water Intake Calculator",
    description: "Calculate your recommended daily water intake based on weight, activity level, and climate.",
    badge: "Personalised",
    category: "health-fitness" as CategoryId,
  },
  {
    href: "/tools/macros-calculator",
    name: "Macros Calculator",
    shortName: "Macro Nutrient Calculator",
    description: "Calculate your daily protein, carbohydrate, and fat targets based on your TDEE and fitness goal.",
    badge: "Protein / Carbs / Fat",
    category: "health-fitness" as CategoryId,
  },
  {
    href: "/tools/due-date-calculator",
    name: "Pregnancy Due Date Calculator",
    shortName: "Due Date Calculator",
    description: "Calculate your estimated due date from your last menstrual period or conception date.",
    badge: "40 weeks",
    category: "health-fitness" as CategoryId,
  },
  {
    href: "/tools/calorie-burn-calculator",
    name: "Calorie Burn Calculator",
    shortName: "Exercise Calorie Burn Calculator",
    description: "Estimate calories burned during 40+ types of exercise using MET (Metabolic Equivalent of Task) values.",
    badge: "MET-based",
    category: "health-fitness" as CategoryId,
  },
  {
    href: "/tools/one-rep-max-calculator",
    name: "One Rep Max Calculator",
    shortName: "1RM Strength Calculator",
    description: "Estimate your one-rep max (1RM) for any lift using Epley, Brzycki, and other validated formulas.",
    badge: "4 formulas",
    category: "health-fitness" as CategoryId,
  },
  {
    href: "/tools/running-pace-calculator",
    name: "Running Pace Calculator",
    shortName: "Running Pace & Speed Calculator",
    description: "Calculate your running pace, speed, or finish time for any distance. Convert between min/km and min/mile.",
    badge: "Any distance",
    category: "health-fitness" as CategoryId,
  },
  {
    href: "/tools/sleep-calculator",
    name: "Sleep Calculator",
    shortName: "Sleep Cycle & Wake Time Calculator",
    description: "Find the best times to wake up or go to sleep based on 90-minute sleep cycles. Avoid waking mid-cycle.",
    badge: "Sleep cycles",
    category: "health-fitness" as CategoryId,
  },
  {
    href: "/tools/protein-intake-calculator",
    name: "Protein Intake Calculator",
    shortName: "Daily Protein Intake Calculator",
    description: "Calculate your optimal daily protein intake based on body weight, activity level, and fitness goal.",
    badge: "Goal-based",
    category: "health-fitness" as CategoryId,
  },
  {
    href: "/tools/debt-payoff-calculator",
    name: "Debt Payoff Calculator",
    shortName: "Debt Avalanche & Snowball Calculator",
    description: "Calculate how long to pay off a debt and total interest paid. Compare avalanche vs snowball strategies.",
    badge: "Avalanche & Snowball",
    category: "finance" as CategoryId,
  },
  {
    href: "/tools/inflation-calculator",
    name: "Inflation Calculator",
    shortName: "Purchasing Power & Inflation Calculator",
    description: "Calculate the purchasing power of money over time using an annual inflation rate. See future or past equivalent values.",
    badge: "Purchasing power",
    category: "finance" as CategoryId,
  },
  {
    href: "/tools/emergency-fund-calculator",
    name: "Emergency Fund Calculator",
    shortName: "Emergency Fund Target Calculator",
    description: "Calculate how large your emergency fund should be and how long it will take to save based on your monthly expenses.",
    badge: "3–6 months",
    category: "finance" as CategoryId,
  },
  {
    href: "/tools/compound-interest-calculator",
    name: "Compound Interest Calculator",
    shortName: "Compound Interest & Growth Calculator",
    description: "Calculate the power of compound interest. Choose compounding frequency: daily, monthly, quarterly, or annually.",
    badge: "Any frequency",
    category: "finance" as CategoryId,
  },
  {
    href: "/tools/tip-split-calculator",
    name: "Tip & Split Calculator",
    shortName: "Restaurant Tip & Bill Splitter",
    description: "Calculate the tip amount and split a restaurant bill between any number of people.",
    badge: "Bill splitter",
    category: "finance" as CategoryId,
  },
  {
    href: "/tools/retirement-calculator",
    name: "Retirement Calculator",
    shortName: "Retirement Savings Calculator",
    description: "Project your retirement nest egg from current savings, monthly contributions, and expected return rate.",
    badge: "Nest egg",
    category: "finance" as CategoryId,
  },
  {
    href: "/tools/loan-comparison",
    name: "Loan Comparison Calculator",
    shortName: "Loan Comparison Tool",
    description: "Compare two loan offers side by side — monthly payment, total interest, and total cost for each.",
    badge: "Side by side",
    category: "finance" as CategoryId,
  },
  {
    href: "/tools/currency-converter",
    name: "Currency Converter",
    shortName: "Currency Converter",
    description: "Convert between 30+ major currencies using mid-market reference rates. Instant, no API, no signup.",
    badge: "30+ currencies",
    category: "finance" as CategoryId,
  },
  {
    href: "/tools/dividend-calculator",
    name: "Dividend Calculator",
    shortName: "Dividend Income Calculator",
    description: "Calculate annual dividend income from shares owned and dividend yield. Includes DRIP reinvestment projection.",
    badge: "DRIP growth",
    category: "finance" as CategoryId,
  },
  {
    href: "/tools/payback-period",
    name: "Payback Period Calculator",
    shortName: "Investment Payback Period",
    description: "Calculate how many years it takes for an investment to pay back its initial cost from expected cash flows.",
    badge: "Break-even years",
    category: "finance" as CategoryId,
  },
  {
    href: "/tools/net-present-value",
    name: "NPV Calculator",
    shortName: "Net Present Value Calculator",
    description: "Calculate the Net Present Value (NPV) and IRR of a series of future cash flows at any discount rate.",
    badge: "IRR included",
    category: "finance" as CategoryId,
  },
  {
    href: "/tools/vo2max-calculator",
    name: "VO2 Max Calculator",
    shortName: "VO2 Max Estimator",
    description: "Estimate your VO2 max from a Cooper 12-minute run, Rockport walk test, or resting heart rate method.",
    badge: "3 test methods",
    category: "health-fitness" as CategoryId,
  },
  {
    href: "/tools/waist-to-hip-ratio",
    name: "Waist-to-Hip Ratio Calculator",
    shortName: "Waist-Hip Ratio & Health Risk",
    description: "Calculate your waist-to-hip ratio and cardiovascular health risk using WHO classification guidelines.",
    badge: "WHO risk bands",
    category: "health-fitness" as CategoryId,
  },
  {
    href: "/tools/lean-body-mass",
    name: "Lean Body Mass Calculator",
    shortName: "Lean Body Mass Calculator",
    description: "Calculate your lean body mass using Boer, James, and Hume formulas. Shows fat mass and body fat percentage.",
    badge: "3 formulas",
    category: "health-fitness" as CategoryId,
  },
  {
    href: "/tools/caloric-deficit-calculator",
    name: "Caloric Deficit Calculator",
    shortName: "Caloric Deficit & Weight Loss Timeline",
    description: "Find out how long it will take to reach your target weight based on a daily caloric deficit.",
    badge: "Week-by-week",
    category: "health-fitness" as CategoryId,
  },
  {
    href: "/tools/pregnancy-weight-gain",
    name: "Pregnancy Weight Gain Calculator",
    shortName: "Gestational Weight Gain Guide",
    description: "Calculate recommended pregnancy weight gain based on pre-pregnancy BMI using IOM 2009 guidelines.",
    badge: "IOM guidelines",
    category: "health-fitness" as CategoryId,
  },
  {
    href: "/tools/menstrual-cycle-calculator",
    name: "Menstrual Cycle Calculator",
    shortName: "Period & Ovulation Calculator",
    description: "Predict your next period, ovulation date, and fertile window based on your average cycle length.",
    badge: "Fertile window",
    category: "health-fitness" as CategoryId,
  },
  // Finance — batch 3
  {
    href: "/tools/home-affordability",
    name: "Home Affordability Calculator",
    shortName: "Home Affordability Calculator",
    description: "Calculate how much house you can afford based on income, debts, down payment, and the 28/36 DTI rule.",
    badge: "28/36 rule",
    category: "finance" as CategoryId,
  },
  {
    href: "/tools/rent-vs-buy",
    name: "Rent vs Buy Calculator",
    shortName: "Rent vs Buy Comparison",
    description: "Compare the total cost of renting vs buying a home over any time horizon. Includes opportunity cost of the down payment.",
    badge: "Break-even year",
    category: "finance" as CategoryId,
  },
  {
    href: "/tools/tax-bracket-calculator",
    name: "Tax Bracket Calculator",
    shortName: "US Federal Tax Bracket Calculator",
    description: "Calculate your 2024 US federal income tax using the official tax brackets. Shows effective rate, marginal rate, and bracket breakdown.",
    badge: "2024 brackets",
    category: "finance" as CategoryId,
  },
  {
    href: "/tools/after-tax-salary",
    name: "After-Tax Salary Calculator",
    shortName: "Take-Home Pay Calculator",
    description: "Calculate your US take-home pay after federal income tax and FICA (Social Security + Medicare). Shows annual, monthly, and hourly net pay.",
    badge: "Net pay",
    category: "finance" as CategoryId,
  },
  {
    href: "/tools/rule-of-72",
    name: "Rule of 72 Calculator",
    shortName: "Rule of 72 — Doubling Time",
    description: "Use the Rule of 72 to estimate how long it takes to double your money at a given return rate — or what rate you need to double in a set number of years.",
    badge: "Instant estimate",
    category: "finance" as CategoryId,
  },
  {
    href: "/tools/debt-to-income-ratio",
    name: "Debt-to-Income Ratio Calculator",
    shortName: "DTI Ratio Calculator",
    description: "Calculate your front-end and back-end debt-to-income (DTI) ratios to see if you qualify for a mortgage or other loans.",
    badge: "Mortgage ready",
    category: "finance" as CategoryId,
  },
  // Health & Fitness — batch 3
  {
    href: "/tools/sleep-debt-calculator",
    name: "Sleep Debt Calculator",
    shortName: "Weekly Sleep Debt Tracker",
    description: "Track how much sleep debt you've accumulated over the week by logging your actual vs target sleep hours each day.",
    badge: "Weekly tracker",
    category: "health-fitness" as CategoryId,
  },
  {
    href: "/tools/keto-macro-calculator",
    name: "Keto Macro Calculator",
    shortName: "Ketogenic Diet Macro Calculator",
    description: "Calculate your ketogenic diet macros — calories, net carbs, protein, and fat — based on your TDEE and the standard keto split.",
    badge: "Net carbs",
    category: "health-fitness" as CategoryId,
  },
  {
    href: "/tools/alcohol-unit-calculator",
    name: "Alcohol Unit Calculator",
    shortName: "Alcohol Units & Drink Tracker",
    description: "Calculate alcohol units in any drink by volume and ABV. Track your weekly total and see how it compares to low-risk guidelines.",
    badge: "Weekly total",
    category: "health-fitness" as CategoryId,
  },
  {
    href: "/tools/one-mile-run-test",
    name: "1-Mile Run Fitness Test",
    shortName: "1-Mile Run VO2 Max Estimator",
    description: "Estimate your VO2 max from your 1-mile run time using the George et al. (1993) validated formula. Shows fitness category by age and gender.",
    badge: "George formula",
    category: "health-fitness" as CategoryId,
  },
  {
    href: "/tools/fiber-intake-calculator",
    name: "Fiber Intake Calculator",
    shortName: "Daily Fiber Intake Calculator",
    description: "Calculate your recommended daily fiber intake by age and gender. Shows how to meet your target with common high-fiber foods.",
    badge: "Food sources",
    category: "health-fitness" as CategoryId,
  },
  {
    href: "/tools/caffeine-calculator",
    name: "Caffeine Calculator",
    shortName: "Safe Caffeine Limit & Timing",
    description: "Calculate your safe daily caffeine limit by body weight and find what time you should stop drinking coffee to sleep by a target bedtime.",
    badge: "Sleep timing",
    category: "health-fitness" as CategoryId,
  },
  // Cooking tools
  {
    href: "/tools/recipe-scaler",
    name: "Recipe Scaler",
    shortName: "Recipe Scaler",
    description: "Scale any recipe up or down by entering your original and target serving sizes. Handles fractions and converts between units.",
    badge: "Any ratio",
    category: "cooking" as CategoryId,
  },
  {
    href: "/tools/cooking-unit-converter",
    name: "Cooking Unit Converter",
    shortName: "Cooking Measurement Converter",
    description: "Convert between all cooking measurements — teaspoons, tablespoons, cups, fluid ounces, millilitres, and litres. Also converts grams, ounces, and pounds.",
    badge: "Volume & weight",
    category: "cooking" as CategoryId,
  },
  {
    href: "/tools/baking-substitutions",
    name: "Baking Substitutions Guide",
    shortName: "Baking Ingredient Substitutions",
    description: "Find substitutes for 30+ common baking ingredients — eggs, buttermilk, baking powder, butter, sugar, cream, and more. Searchable and instant.",
    badge: "30+ ingredients",
    category: "cooking" as CategoryId,
  },
  {
    href: "/tools/oven-temperature-converter",
    name: "Oven Temperature Converter",
    shortName: "Oven Temp — °F / °C / Gas Mark",
    description: "Convert oven temperatures between Fahrenheit, Celsius, fan (convection) Celsius, and Gas Mark. Includes a full reference table for common baking temperatures.",
    badge: "Gas Mark too",
    category: "cooking" as CategoryId,
  },
  {
    href: "/tools/yeast-converter",
    name: "Yeast Converter",
    shortName: "Yeast Conversion Calculator",
    description: "Convert between active dry yeast, instant (rapid-rise) yeast, and fresh yeast. Enter any amount in any form to get all three equivalents instantly.",
    badge: "3 yeast types",
    category: "cooking" as CategoryId,
  },
  {
    href: "/tools/butter-converter",
    name: "Butter Converter",
    shortName: "Butter Measurement Converter",
    description: "Convert butter between sticks, cups, tablespoons, ounces, and grams. Essential for adapting US recipes to metric measurements.",
    badge: "Sticks to grams",
    category: "cooking" as CategoryId,
  },
  {
    href: "/tools/meat-temperature-guide",
    name: "Meat Temperature Guide",
    shortName: "Safe Meat Cooking Temperatures",
    description: "USDA-recommended safe internal cooking temperatures for all meats — beef, chicken, pork, fish, lamb, and more. Includes rare to well-done guide for beef.",
    badge: "USDA safe temps",
    category: "cooking" as CategoryId,
  },
  {
    href: "/tools/coffee-ratio-calculator",
    name: "Coffee Ratio Calculator",
    shortName: "Coffee to Water Ratio Guide",
    description: "Calculate the perfect coffee-to-water ratio for 8 brew methods — espresso, pour over, French press, AeroPress, cold brew, drip, Moka pot, and Turkish.",
    badge: "8 brew methods",
    category: "cooking" as CategoryId,
  },
] as const;

export type Tool = (typeof TOOLS)[number];

export const CATEGORY_METADATA = [
  {
    id: "image-tools" as CategoryId,
    label: "Image Tools",
    href: "/image-tools",
    description: "Crop, resize, compress, watermark, flip, and transform images entirely in your browser. No upload, no account.",
    seoTitle: "Free Online Image Tools — Crop, Resize, Compress & More | Pix Garage",
    seoDescription: "Free in-browser image tools: crop, resize, compress, watermark, flip, rotate, add borders, remove backgrounds, and more. No upload required.",
  },
  {
    id: "pdf-tools" as CategoryId,
    label: "PDF Tools",
    href: "/pdf-tools",
    description: "Merge, split, rotate, protect, sign, annotate, and edit PDF files — all processed locally in your browser.",
    seoTitle: "Free Online PDF Tools — Merge, Split, Sign, Edit & More | Pix Garage",
    seoDescription: "Free in-browser PDF tools: merge, split, rotate, protect, unlock, sign, watermark, add page numbers, edit, and compare PDFs. No upload needed.",
  },
  {
    id: "pdf" as CategoryId,
    label: "Image to PDF",
    href: "/image-to-pdf",
    description: "Convert JPG, PNG, WebP, HEIC, BMP, TIFF, SVG, GIF, and more to PDF instantly. One click, no upload.",
    seoTitle: "Convert Images to PDF Free — JPG, PNG, WebP, HEIC & More | Pix Garage",
    seoDescription: "Convert any image format to PDF in your browser. Supports JPG, PNG, WebP, HEIC, BMP, TIFF, SVG, GIF, AVIF, and ICO. No upload, instant results.",
  },
  {
    id: "webp" as CategoryId,
    label: "WebP Tools",
    href: "/webp-tools",
    description: "Convert PNG, JPG, HEIC, GIF, BMP, TIFF, SVG, and more to WebP for dramatically smaller file sizes.",
    seoTitle: "Free WebP Converter Tools — PNG, JPG, HEIC to WebP | Pix Garage",
    seoDescription: "Convert any image format to WebP for smaller file sizes and faster web performance. Supports PNG, JPG, GIF, HEIC, BMP, TIFF, SVG, AVIF, and more.",
  },
  {
    id: "qr" as CategoryId,
    label: "QR Code Tools",
    href: "/qr-tools",
    description: "Generate, decode, and customise QR codes for URLs, WiFi, contacts, email, and phone numbers.",
    seoTitle: "Free QR Code Generator & Reader Tools | Pix Garage",
    seoDescription: "Generate QR codes for URLs, WiFi, email, phone, and contacts. Decode any QR code from an image. Add your logo to QR codes. All free, no account needed.",
  },
  {
    id: "color-tools" as CategoryId,
    label: "Color Tools",
    href: "/color-tools",
    description: "Pick colors, build palettes, check WCAG contrast, generate gradients, shadows, and tint/shade scales.",
    seoTitle: "Free Online Color Tools — Picker, Palettes, Contrast Checker | Pix Garage",
    seoDescription: "Free color tools: color picker, palette generator, WCAG contrast checker, gradient builder, shadow generator, tint/shade scales, and color blindness simulator.",
  },
  {
    id: "text-tools" as CategoryId,
    label: "Text Tools",
    href: "/text-tools",
    description: "Write, transform, and analyse text — generate lorem ipsum, convert case, count words, encode data, create ASCII art, test regex, preview Markdown, and more.",
    seoTitle: "Free Online Text Tools — 31 Tools for Writers & Developers | Pix Garage",
    seoDescription: "Free in-browser text tools: word counter, case converter, lorem ipsum, base64, URL encoder, UUID generator, diff checker, regex tester, markdown preview, morse code, ASCII art, number to words, char frequency, and more. No upload, no signup.",
  },
  {
    id: "dev-tools" as CategoryId,
    label: "Developer Tools",
    href: "/dev-tools",
    description: "Convert CSV to JSON, decode JWTs, explain cron expressions, convert Unix timestamps, and more — all in-browser, zero dependencies.",
    seoTitle: "Free Developer Tools — CSV to JSON, JWT Decoder, Crontab | Pix Garage",
    seoDescription: "Free in-browser developer tools: CSV to JSON, JSON to CSV, JWT decoder, crontab expression explainer, and Unix timestamp converter. No signup, no server uploads.",
  },
  {
    id: "unit-converter" as CategoryId,
    label: "Unit Converter",
    href: "/unit-converter",
    description: "Convert length, weight, temperature, speed, area, volume, pressure, energy, data, time, angle, and fuel efficiency — all in-browser.",
    seoTitle: "Free Unit Converters — Length, Weight, Speed, Volume & More | Pix Garage",
    seoDescription: "Free in-browser unit converters: length, weight, temperature, speed, area, volume, pressure, energy, data storage, time, angle, and fuel efficiency. Instant, no signup.",
  },
  {
    id: "calculators" as CategoryId,
    label: "Calculators",
    href: "/calculators",
    description: "23 free in-browser calculators — percentage, tip, BMI, compound interest, loan, age, date difference, discount, sales tax, calorie, fuel cost, hours, unit price, electricity, salary, margin, ROI, savings goal, GPA, grade, speed, paint, and concrete. Instant results as you type.",
    seoTitle: "Free Online Calculators — Percentage, Tip, BMI, Salary, GPA & More | Pix Garage",
    seoDescription: "23 free in-browser calculators: percentage, tip, BMI, compound interest, loan, age, date difference, discount, sales tax, calorie (BMR/TDEE), fuel cost, hours worked, unit price, electricity cost, salary, margin, ROI, savings goal, GPA, grade, speed, paint, and concrete. No signup.",
  },
  {
    id: "math-tools" as CategoryId,
    label: "Math Tools",
    href: "/math-tools",
    description: "8 free in-browser math tools — fraction calculator, quadratic formula, prime factorization, LCM/GCD, scientific notation, Pythagorean theorem, Roman numerals, and Fibonacci sequence.",
    seoTitle: "Free Online Math Tools — Fractions, Quadratic Formula, Prime Factorization & More | Pix Garage",
    seoDescription: "Free in-browser math tools: fraction calculator, quadratic formula solver, prime factorization, LCM and GCD calculator, scientific notation converter, Pythagorean theorem, Roman numeral converter, and Fibonacci generator. No signup.",
  },
  {
    id: "finance" as CategoryId,
    label: "Finance",
    href: "/finance",
    description: "23 free in-browser finance tools — mortgage, break-even, VAT, net worth, investment, budget, debt payoff, inflation, emergency fund, compound interest, tip splitter, retirement, loan comparison, currency converter, dividends, payback period, NPV, home affordability, rent vs buy, tax brackets, take-home pay, Rule of 72, and DTI ratio.",
    seoTitle: "Free Online Finance Calculators — Mortgage, Tax, Retirement, NPV & More | Pix Garage",
    seoDescription: "Free in-browser finance calculators: mortgage, break-even, VAT, net worth, investment, budget, debt payoff, inflation, emergency fund, compound interest, tip splitter, retirement savings, loan comparison, currency converter, dividends, payback period, NPV, home affordability, rent vs buy, tax brackets, take-home pay, Rule of 72, and DTI ratio. No signup.",
  },
  {
    id: "health-fitness" as CategoryId,
    label: "Health & Fitness",
    href: "/health-fitness",
    description: "23 free in-browser health tools — ideal weight, body fat, heart rate zones, water intake, macros, due date, calorie burn, 1RM, running pace, sleep, protein, VO2 max, waist-hip ratio, lean mass, caloric deficit, pregnancy weight gain, cycle tracker, sleep debt, keto macros, alcohol units, 1-mile run, fiber, and caffeine.",
    seoTitle: "Free Online Health & Fitness Calculators — VO2 Max, Keto, Caffeine, Body Fat & More | Pix Garage",
    seoDescription: "Free in-browser health calculators: ideal weight, body fat (Navy), heart rate zones, water intake, macros, due date, calorie burn, 1RM, running pace, sleep cycles, protein, VO2 max, waist-to-hip ratio, lean body mass, caloric deficit, pregnancy weight gain, period tracker, sleep debt, keto macros, alcohol units, 1-mile run test, fiber intake, and caffeine limit. No signup.",
  },
  {
    id: "cooking" as CategoryId,
    label: "Cooking",
    href: "/cooking",
    description: "8 free in-browser cooking tools — recipe scaler, cooking unit converter, baking substitutions, oven temperature converter, yeast converter, butter converter, meat temperature guide, and coffee ratio calculator.",
    seoTitle: "Free Online Cooking Tools — Recipe Scaler, Substitutions, Oven Temp & More | Pix Garage",
    seoDescription: "Free in-browser cooking tools: recipe scaler, cooking unit converter (cups/tbsp/ml/g), baking ingredient substitutions, oven temperature converter (°F/°C/Gas Mark), yeast converter, butter converter, safe meat cooking temperatures, and coffee-to-water ratio calculator. No signup.",
  },
] as const;

export type CategoryMetadata = (typeof CATEGORY_METADATA)[number];
