import type { MetadataRoute } from "next";

export const dynamic = "force-static";

const BASE = "https://pixgarage.com";

const TOOL_PATHS = [
  "/tools/png-to-webp",
  "/tools/jpg-to-webp",
  "/tools/gif-to-webp",
  "/tools/avif-to-webp",
  "/tools/bmp-to-webp",
  "/tools/tiff-to-webp",
  "/tools/svg-to-webp",
  "/tools/ico-to-webp",
  "/tools/jfif-to-webp",
  "/tools/pdf-to-webp",
  "/tools/webp-to-webp",
  "/tools/webp-resizer",
  "/tools/png-resizer",
  "/tools/jpg-resizer",
  "/tools/heic-resizer",
  "/tools/heic-to-webp",
  "/tools/heic-to-png",
  "/tools/heic-to-jpg",
  "/tools/html-to-pdf",
  "/tools/jpg-to-pdf",
  "/tools/png-to-pdf",
  "/tools/webp-to-pdf",
  "/tools/heic-to-pdf",
  "/tools/bmp-to-pdf",
  "/tools/tiff-to-pdf",
  "/tools/gif-to-pdf",
  "/tools/svg-to-pdf",
  "/tools/avif-to-pdf",
  "/tools/ico-to-pdf",
  "/tools/jfif-to-pdf",
  "/tools/merge-pdf",
  "/tools/split-pdf",
  "/tools/rotate-pdf",
  "/tools/protect-pdf",
  "/tools/unlock-pdf",
  "/tools/watermark-pdf",
  "/tools/pdf-page-numbers",
  "/tools/crop-pdf",
  "/tools/rearrange-pdf",
  "/tools/pdf-to-images",
  "/tools/sign-pdf",
  "/tools/ocr-pdf",
  "/tools/edit-pdf",
  "/tools/compare-pdf",
  "/tools/qr-code-generator",
  "/tools/qr-code-reader",
  "/tools/qr-code-with-logo",
  "/tools/batch-qr-generator",
  "/tools/vcard-qr-generator",
  "/tools/image-compressor",
  "/tools/image-cropper",
  "/tools/background-remover",
  "/tools/favicon-generator",
  "/tools/image-flip-rotate",
  "/tools/photo-adjustments",
  "/tools/image-watermark",
  "/tools/image-resizer",
  "/tools/rounded-corners",
  "/tools/color-palette",
  "/tools/image-border",
  "/tools/image-collage",
  "/tools/grayscale-tint",
  "/tools/social-media-resizer",
  "/tools/image-padding",
  "/tools/image-to-base64",
  "/tools/noise-grain",
  "/tools/color-picker",
  "/tools/gradient-generator",
  "/tools/contrast-checker",
  "/tools/color-palette-generator",
  "/tools/tint-shade-generator",
  "/tools/color-blindness-simulator",
  "/tools/shadow-generator",
  "/tools/random-color-generator",
  "/tools/color-converter",
  "/tools/color-mixer",
  "/tools/color-name-finder",
  "/tools/image-color-picker",
  "/tools/opacity-calculator",
  "/tools/lorem-ipsum",
  "/tools/text-case-converter",
  "/tools/word-counter",
  "/tools/plagiarism-checker",
  "/tools/fancy-text",
  "/tools/bold-text-generator",
  "/tools/italic-text-generator",
  "/tools/strikethrough-text",
  "/tools/stylish-name-generator",
  "/tools/free-fire-name-generator",
  "/tools/pubg-name-generator",
  "/tools/password-generator",
  "/tools/hashtag-generator",
  "/tools/reverse-text",
  "/tools/text-repeater",
  "/tools/random-name-generator",
  "/tools/json-formatter",
  "/tools/base64-text",
  "/tools/url-encoder",
  "/tools/uuid-generator",
  "/tools/diff-checker",
  "/tools/leet-speak",
  "/tools/morse-code",
  "/tools/emoji-text",
  "/tools/rot13",
  "/tools/markdown-preview",
  "/tools/html-encoder",
  "/tools/regex-tester",
  "/tools/number-to-words",
  "/tools/ascii-art",
  "/tools/char-frequency",
  "/tools/text-to-slug",
  "/tools/csv-to-json",
  "/tools/json-to-csv",
  "/tools/crontab-explainer",
  "/tools/unix-timestamp",
  "/tools/jwt-decoder",
  "/tools/length-converter",
  "/tools/weight-converter",
  "/tools/temperature-converter",
  "/tools/speed-converter",
  "/tools/area-converter",
  "/tools/volume-converter",
  "/tools/pressure-converter",
  "/tools/energy-converter",
  "/tools/data-storage-converter",
  "/tools/time-converter",
  "/tools/angle-converter",
  "/tools/fuel-converter",
  "/tools/yaml-to-json",
  "/tools/xml-formatter",
  "/tools/string-escape",
  "/tools/base-converter",
  "/tools/percentage-calculator",
  "/tools/tip-calculator",
  "/tools/bmi-calculator",
  "/tools/compound-interest",
  "/tools/loan-calculator",
  "/tools/age-calculator",
  "/tools/date-difference",
  "/tools/discount-calculator",
  "/tools/sales-tax-calculator",
  "/tools/calorie-calculator",
  "/tools/fuel-cost-calculator",
  "/tools/hours-calculator",
  "/tools/unit-price-calculator",
  "/tools/electricity-cost-calculator",
  "/tools/salary-calculator",
  "/tools/margin-calculator",
  "/tools/roi-calculator",
  "/tools/savings-goal-calculator",
  "/tools/gpa-calculator",
  "/tools/readability-score",
  "/tools/syllable-counter",
  "/tools/reading-time",
  "/tools/sentence-counter",
  "/tools/text-to-speech",
  "/tools/hash-generator",
  "/tools/url-parser",
  "/tools/color-code-converter",
  "/tools/html-minifier",
  "/tools/markdown-to-html",
  "/tools/grade-calculator",
  "/tools/speed-calculator",
  "/tools/paint-calculator",
  "/tools/concrete-calculator",
  "/tools/fraction-calculator",
  "/tools/quadratic-formula",
  "/tools/prime-factorization",
  "/tools/lcm-gcd-calculator",
  "/tools/scientific-notation",
  "/tools/pythagorean-theorem",
  "/tools/roman-numeral-converter",
  "/tools/fibonacci-generator",
  "/tools/mortgage-calculator",
  "/tools/break-even-calculator",
  "/tools/vat-calculator",
  "/tools/net-worth-calculator",
  "/tools/investment-calculator",
  "/tools/budget-calculator",
  "/tools/ideal-weight-calculator",
  "/tools/body-fat-calculator",
  "/tools/heart-rate-zones",
  "/tools/water-intake-calculator",
  "/tools/macros-calculator",
  "/tools/due-date-calculator",
  "/tools/calorie-burn-calculator",
  "/tools/one-rep-max-calculator",
  "/tools/running-pace-calculator",
  "/tools/sleep-calculator",
  "/tools/protein-intake-calculator",
  "/tools/debt-payoff-calculator",
  "/tools/inflation-calculator",
  "/tools/emergency-fund-calculator",
  "/tools/compound-interest-calculator",
  "/tools/tip-split-calculator",
  "/tools/retirement-calculator",
  "/tools/loan-comparison",
  "/tools/currency-converter",
  "/tools/dividend-calculator",
  "/tools/payback-period",
  "/tools/net-present-value",
  "/tools/vo2max-calculator",
  "/tools/waist-to-hip-ratio",
  "/tools/lean-body-mass",
  "/tools/caloric-deficit-calculator",
  "/tools/pregnancy-weight-gain",
  "/tools/menstrual-cycle-calculator",
  "/tools/home-affordability",
  "/tools/rent-vs-buy",
  "/tools/tax-bracket-calculator",
  "/tools/after-tax-salary",
  "/tools/rule-of-72",
  "/tools/debt-to-income-ratio",
  "/tools/sleep-debt-calculator",
  "/tools/keto-macro-calculator",
  "/tools/alcohol-unit-calculator",
  "/tools/one-mile-run-test",
  "/tools/fiber-intake-calculator",
  "/tools/caffeine-calculator",
  "/tools/recipe-scaler",
  "/tools/cooking-unit-converter",
  "/tools/baking-substitutions",
  "/tools/oven-temperature-converter",
  "/tools/yeast-converter",
  "/tools/butter-converter",
  "/tools/meat-temperature-guide",
  "/tools/coffee-ratio-calculator",
];

const STATIC_PAGES = [
  { path: "", priority: 1 },
  { path: "/tools", priority: 0.95 },
  { path: "/image-tools", priority: 0.9 },
  { path: "/pdf-tools", priority: 0.9 },
  { path: "/image-to-pdf", priority: 0.9 },
  { path: "/webp-tools", priority: 0.9 },
  { path: "/qr-tools", priority: 0.9 },
  { path: "/color-tools", priority: 0.9 },
  { path: "/text-tools", priority: 0.9 },
  { path: "/dev-tools", priority: 0.9 },
  { path: "/unit-converter", priority: 0.9 },
  { path: "/calculators", priority: 0.9 },
  { path: "/math-tools", priority: 0.9 },
  { path: "/finance", priority: 0.9 },
  { path: "/health-fitness", priority: 0.9 },
  { path: "/cooking", priority: 0.9 },
  { path: "/about", priority: 0.5 },
  { path: "/security", priority: 0.4 },
  { path: "/contact", priority: 0.4 },
  { path: "/privacy", priority: 0.3 },
];

export default function sitemap(): MetadataRoute.Sitemap {
  const tools = TOOL_PATHS.map((path) => ({
    url: `${BASE}${path}`,
    lastModified: new Date(),
    changeFrequency: "monthly" as const,
    priority: 0.9,
  }));

  const statics = STATIC_PAGES.map(({ path, priority }) => ({
    url: `${BASE}${path}`,
    lastModified: new Date(),
    changeFrequency: "yearly" as const,
    priority,
  }));

  return [...statics, ...tools];
}
